package ch.uzh.ifi.seal.soprafs20.constant;

public enum PlayerStatus
{
    JOINED, READY, PLAYING, FINISHED, LEFT,
    PICKING_NUMBER, WAITING_FOR_NUMBER,
    WAITING_FOR_CLUES, WRITING_CLUES,
    WAITING_FOR_REVIEW, REVIEWING_CLUES,
    GUESSING_WORD, WAITING_FOR_GUESS,
    END_OF_TURN

}
