insert into card(id, drawn, language) values(1, false, 0);
insert into card(id, drawn, language) values(2, false, 0);
insert into card(id, drawn, language) values(3, false, 0);
insert into card(id, drawn, language) values(4, false, 0);
insert into card(id, drawn, language) values(5, false, 0);
insert into card(id, drawn, language) values(6, false, 0);
insert into card(id, drawn, language) values(7, false, 0);
insert into card(id, drawn, language) values(8, false, 0);
insert into card(id, drawn, language) values(9, false, 0);
insert into card(id, drawn, language) values(10, false, 0);
insert into card(id, drawn, language) values(11, false, 0);
insert into card(id, drawn, language) values(12, false, 0);
insert into card(id, drawn, language) values(13, false, 0);
insert into card(id, drawn, language) values(14, false, 0);
insert into card(id, drawn, language) values(15, false, 0);
insert into card(id, drawn, language) values(16, false, 0);
insert into card(id, drawn, language) values(17, false, 0);
insert into card(id, drawn, language) values(18, false, 0);
insert into card(id, drawn, language) values(19, false, 0);


insert into card(id, drawn, language) values(94, false, 0);
insert into card(id, drawn, language) values(95, false, 0);
insert into card(id, drawn, language) values(96, false, 0);
insert into card(id, drawn, language) values(97, false, 0);
insert into card(id, drawn, language) values(98, false, 0);
insert into card(id, drawn, language) values(99, false, 0);
insert into card(id, drawn, language) values(100, false, 0);
insert into card(id, drawn, language) values(101, false, 0);
insert into card(id, drawn, language) values(102, false, 0);
insert into card(id, drawn, language) values(103, false, 0);
insert into card(id, drawn, language) values(104, false, 0);
insert into card(id, drawn, language) values(105, false, 0);
insert into card(id, drawn, language) values(106, false, 0);
insert into card(id, drawn, language) values(107, false, 0);
insert into card(id, drawn, language) values(108, false, 0);
insert into card(id, drawn, language) values(109, false, 0);
insert into card(id, drawn, language) values(110, false, 0);
insert into card(id, drawn, language) values(111, false, 0);
insert into card(id, drawn, language) values(112, false, 0);
insert into card(id, drawn, language) values(113, false, 0);
insert into card(id, drawn, language) values(114, false, 0);
insert into card(id, drawn, language) values(115, false, 0);
insert into card(id, drawn, language) values(116, false, 0);
insert into card(id, drawn, language) values(117, false, 0);
insert into card(id, drawn, language) values(118, false, 0);
insert into card(id, drawn, language) values(119, false, 0);
insert into card(id, drawn, language) values(120, false, 0);
insert into card(id, drawn, language) values(121, false, 0);
insert into card(id, drawn, language) values(122, false, 0);
insert into card(id, drawn, language) values(123, false, 0);
insert into card(id, drawn, language) values(124, false, 0);
insert into card(id, drawn, language) values(125, false, 0);
insert into card(id, drawn, language) values(126, false, 0);
insert into card(id, drawn, language) values(127, false, 0);
insert into card(id, drawn, language) values(128, false, 0);
insert into card(id, drawn, language) values(129, false, 0);

insert into mysteryword (card_id, word, number, status) values(1, 'Alcatraz', 1, 0);
insert into mysteryword (card_id, word, number, status) values(1, 'Rauch', 2, 0);
insert into mysteryword (card_id, word, number, status) values(1, 'Haselnuss', 3, 0);
insert into mysteryword (card_id, word, number, status) values(1, 'Diamant', 4, 0);
insert into mysteryword (card_id, word, number, status) values(1, 'Rose', 5, 0);
insert into mysteryword (card_id, word, number, status) values(2, 'Marionette', 1, 0);
insert into mysteryword (card_id, word, number, status) values(2, 'Spiel', 2, 0);
insert into mysteryword (card_id, word, number, status) values(2, 'Vegas', 3, 0);
insert into mysteryword (card_id, word, number, status) values(2, 'Truhe', 4, 0);
insert into mysteryword (card_id, word, number, status) values(2, 'Flugzeug', 5, 0);
insert into mysteryword (card_id, word, number, status) values(3, 'Schnur', 1, 0);
insert into mysteryword (card_id, word, number, status) values(3, 'Australien', 2, 0);
insert into mysteryword (card_id, word, number, status) values(3, 'Schloss', 3, 0);
insert into mysteryword (card_id, word, number, status) values(3, 'Wache', 4, 0);
insert into mysteryword (card_id, word, number, status) values(3, 'Schaf', 5, 0);
insert into mysteryword (card_id, word, number, status) values(4, 'Fleece', 1, 0);
insert into mysteryword (card_id, word, number, status) values(4, 'Maus', 2, 0);
insert into mysteryword (card_id, word, number, status) values(4, 'Kette', 3, 0);
insert into mysteryword (card_id, word, number, status) values(4, 'Bauernhof', 4, 0);
insert into mysteryword (card_id, word, number, status) values(4, 'Belgien', 5, 0);
insert into mysteryword (card_id, word, number, status) values(5, 'Pfeffer', 1, 0);
insert into mysteryword (card_id, word, number, status) values(5, 'Dreieck', 2, 0);
insert into mysteryword (card_id, word, number, status) values(5, 'Puppe', 3, 0);
insert into mysteryword (card_id, word, number, status) values(5, 'Italien', 4, 0);
insert into mysteryword (card_id, word, number, status) values(5, 'Bühne', 5, 0);
insert into mysteryword (card_id, word, number, status) values(6, 'Herz', 1, 0);
insert into mysteryword (card_id, word, number, status) values(6, 'Moskau', 2, 0);
insert into mysteryword (card_id, word, number, status) values(6, 'Billard', 3, 0);
insert into mysteryword (card_id, word, number, status) values(6, 'Einhorn', 4, 0);
insert into mysteryword (card_id, word, number, status) values(6, 'Orange', 5, 0);
insert into mysteryword (card_id, word, number, status) values(7, 'Tokio', 1, 0);
insert into mysteryword (card_id, word, number, status) values(7, 'Ferse', 2, 0);
insert into mysteryword (card_id, word, number, status) values(7, 'Huhn', 3, 0);
insert into mysteryword (card_id, word, number, status) values(7, 'Helikopter', 4, 0);
insert into mysteryword (card_id, word, number, status) values(7, 'Offizier', 5, 0);
insert into mysteryword (card_id, word, number, status) values(8, 'Melone', 1, 0);
insert into mysteryword (card_id, word, number, status) values(8, 'Anker', 2, 0);
insert into mysteryword (card_id, word, number, status) values(8, 'Israel', 3, 0);
insert into mysteryword (card_id, word, number, status) values(8, 'Kaktus', 4, 0);
insert into mysteryword (card_id, word, number, status) values(8, 'Tennis', 5, 0);
insert into mysteryword (card_id, word, number, status) values(9, 'Frankreich', 1, 0);
insert into mysteryword (card_id, word, number, status) values(9, 'Mond', 2, 0);
insert into mysteryword (card_id, word, number, status) values(9, 'Kantine', 3, 0);
insert into mysteryword (card_id, word, number, status) values(9, 'Kaiserpinguin', 4, 0);
insert into mysteryword (card_id, word, number, status) values(9, 'Werkzeug', 5, 0);
insert into mysteryword (card_id, word, number, status) values(10, 'Gehirn', 1, 0);
insert into mysteryword (card_id, word, number, status) values(10, 'Maske', 2, 0);
insert into mysteryword (card_id, word, number, status) values(10, 'Konzert', 3, 0);
insert into mysteryword (card_id, word, number, status) values(10, 'Troja', 4, 0);
insert into mysteryword (card_id, word, number, status) values(10, 'Hai', 5, 0);
insert into mysteryword (card_id, word, number, status) values(11, 'Musik', 1, 0);
insert into mysteryword (card_id, word, number, status) values(11, 'Hals', 2, 0);
insert into mysteryword (card_id, word, number, status) values(11, 'Amerika', 3, 0);
insert into mysteryword (card_id, word, number, status) values(11, 'Kaffee', 4, 0);
insert into mysteryword (card_id, word, number, status) values(11, 'Fieber', 5, 0);
insert into mysteryword (card_id, word, number, status) values(12, 'Barbie', 1, 0);
insert into mysteryword (card_id, word, number, status) values(12, 'Schokolade', 2, 0);
insert into mysteryword (card_id, word, number, status) values(12, 'Schnee', 3, 0);
insert into mysteryword (card_id, word, number, status) values(12, 'Krawatte', 4, 0);
insert into mysteryword (card_id, word, number, status) values(12, 'Wind', 5, 0);
insert into mysteryword (card_id, word, number, status) values(13, 'Gedanke', 1, 0);
insert into mysteryword (card_id, word, number, status) values(13, 'Frankenstein', 2, 0);
insert into mysteryword (card_id, word, number, status) values(13, 'Strahl', 3, 0);
insert into mysteryword (card_id, word, number, status) values(13, 'Akzent', 4, 0);
insert into mysteryword (card_id, word, number, status) values(13, 'Dusche', 5, 0);
insert into mysteryword (card_id, word, number, status) values(14, 'Marienkäfer', 1, 0);
insert into mysteryword (card_id, word, number, status) values(14, 'Senf', 2, 0);
insert into mysteryword (card_id, word, number, status) values(14, 'Sherlock', 3, 0);
insert into mysteryword (card_id, word, number, status) values(14, 'Flasche', 4, 0);
insert into mysteryword (card_id, word, number, status) values(14, 'Virus', 5, 0);
insert into mysteryword (card_id, word, number, status) values(15, 'Gift', 1, 0);
insert into mysteryword (card_id, word, number, status) values(15, 'Stern', 2, 0);
insert into mysteryword (card_id, word, number, status) values(15, 'Wolf', 3, 0);
insert into mysteryword (card_id, word, number, status) values(15, 'Lena', 4, 0);
insert into mysteryword (card_id, word, number, status) values(15, 'Geburtstag', 5, 0);
insert into mysteryword (card_id, word, number, status) values(16, 'Bäcker', 1, 0);
insert into mysteryword (card_id, word, number, status) values(16, 'Parfüm', 2, 0);
insert into mysteryword (card_id, word, number, status) values(16, 'Flamme', 3, 0);
insert into mysteryword (card_id, word, number, status) values(16, 'Zombie', 4, 0);
insert into mysteryword (card_id, word, number, status) values(16, 'Joker', 5, 0);
insert into mysteryword (card_id, word, number, status) values(17, 'Buffy', 1, 0);
insert into mysteryword (card_id, word, number, status) values(17, 'Vulkan', 2, 0);
insert into mysteryword (card_id, word, number, status) values(17, 'Leidenschaft', 3, 0);
insert into mysteryword (card_id, word, number, status) values(17, 'Hahn', 4, 0);
insert into mysteryword (card_id, word, number, status) values(17, 'Elektrizität', 5, 0);
insert into mysteryword (card_id, word, number, status) values(18, 'Genie', 1, 0);
insert into mysteryword (card_id, word, number, status) values(18, 'Dracula', 2, 0);
insert into mysteryword (card_id, word, number, status) values(18, 'Löwe', 3, 0);
insert into mysteryword (card_id, word, number, status) values(18, 'Socke rFreitag', 4, 0);
insert into mysteryword (card_id, word, number, status) values(18, 'Pirat', 5, 0);
insert into mysteryword (card_id, word, number, status) values(19, 'Ferien', 1, 0);
insert into mysteryword (card_id, word, number, status) values(19, 'Elfe', 2, 0);
insert into mysteryword (card_id, word, number, status) values(19, 'Magnet', 3, 0);
insert into mysteryword (card_id, word, number, status) values(19, 'Gabel', 4, 0);
insert into mysteryword (card_id, word, number, status) values(19, 'Sirup', 5, 0);

insert into mysteryword (card_id, word, number, status) values(94, 'Wald', 1, 0);
insert into mysteryword (card_id, word, number, status) values(94, 'Waage', 2, 0);
insert into mysteryword (card_id, word, number, status) values(94, 'Zeus', 3, 0);
insert into mysteryword (card_id, word, number, status) values(94, 'Kakerlake', 4, 0);
insert into mysteryword (card_id, word, number, status) values(94, 'Dinosaurier', 5, 0);
insert into mysteryword (card_id, word, number, status) values(95, 'Gelb', 1, 0);
insert into mysteryword (card_id, word, number, status) values(95, 'Pilz', 2, 0);
insert into mysteryword (card_id, word, number, status) values(95, 'Taube', 3, 0);
insert into mysteryword (card_id, word, number, status) values(95, 'Pikachu', 4, 0);
insert into mysteryword (card_id, word, number, status) values(95, 'Asterix', 5, 0);
insert into mysteryword (card_id, word, number, status) values(96, 'Roboter', 1, 0);
insert into mysteryword (card_id, word, number, status) values(96, 'Komödie', 2, 0);
insert into mysteryword (card_id, word, number, status) values(96, 'Sprache', 3, 0);
insert into mysteryword (card_id, word, number, status) values(96, 'Friseur', 4, 0);
insert into mysteryword (card_id, word, number, status) values(96, 'Cocktail', 5, 0);
insert into mysteryword (card_id, word, number, status) values(97, 'Mario', 1, 0);
insert into mysteryword (card_id, word, number, status) values(97, 'Korken', 2, 0);
insert into mysteryword (card_id, word, number, status) values(97, 'Geige', 3, 0);
insert into mysteryword (card_id, word, number, status) values(97, 'Pfirsich', 4, 0);
insert into mysteryword (card_id, word, number, status) values(97, 'Fuchs', 5, 0);
insert into mysteryword (card_id, word, number, status) values(98, 'Polizei', 1, 0);
insert into mysteryword (card_id, word, number, status) values(98, 'Simpson', 2, 0);
insert into mysteryword (card_id, word, number, status) values(98, 'Donut', 3, 0);
insert into mysteryword (card_id, word, number, status) values(98, 'Zeitung', 4, 0);
insert into mysteryword (card_id, word, number, status) values(98, 'Berge', 5, 0);
insert into mysteryword (card_id, word, number, status) values(99, 'Erdnuss', 1, 0);
insert into mysteryword (card_id, word, number, status) values(99, 'Glühbirne', 2, 0);
insert into mysteryword (card_id, word, number, status) values(99, 'Jedi', 3, 0);
insert into mysteryword (card_id, word, number, status) values(99, 'Chili', 4, 0);
insert into mysteryword (card_id, word, number, status) values(99, 'Sombrero', 5, 0);
insert into mysteryword (card_id, word, number, status) values(100, 'Kleeblatt', 1, 0);
insert into mysteryword (card_id, word, number, status) values(100, 'Taste', 2, 0);
insert into mysteryword (card_id, word, number, status) values(100, 'Käse', 3, 0);
insert into mysteryword (card_id, word, number, status) values(100, 'Chewbacca', 4, 0);
insert into mysteryword (card_id, word, number, status) values(100, 'Revolver', 5, 0);
insert into mysteryword (card_id, word, number, status) values(101, 'Doktor', 1, 0);
insert into mysteryword (card_id, word, number, status) values(101, 'Erdbeere', 2, 0);
insert into mysteryword (card_id, word, number, status) values(101, 'Kernkraft', 3, 0);
insert into mysteryword (card_id, word, number, status) values(101, 'Lotterie', 4, 0);
insert into mysteryword (card_id, word, number, status) values(101, 'Friedhof', 5, 0);
insert into mysteryword (card_id, word, number, status) values(102, 'Amor', 1, 0);
insert into mysteryword (card_id, word, number, status) values(102, 'Regenschirm', 2, 0);
insert into mysteryword (card_id, word, number, status) values(102, 'Sprung', 3, 0);
insert into mysteryword (card_id, word, number, status) values(102, 'Wurzel', 4, 0);
insert into mysteryword (card_id, word, number, status) values(102, 'Schatz', 5, 0);
insert into mysteryword (card_id, word, number, status) values(103, 'Pilot', 1, 0);
insert into mysteryword (card_id, word, number, status) values(103, 'Micky', 2, 0);
insert into mysteryword (card_id, word, number, status) values(103, 'Kanalisation', 3, 0);
insert into mysteryword (card_id, word, number, status) values(103, 'Galaxie', 4, 0);
insert into mysteryword (card_id, word, number, status) values(103, 'Schnurrbart', 5, 0);
insert into mysteryword (card_id, word, number, status) values(104, 'Blase', 1, 0);
insert into mysteryword (card_id, word, number, status) values(104, 'Kette', 2, 0);
insert into mysteryword (card_id, word, number, status) values(104, 'Stark', 3, 0);
insert into mysteryword (card_id, word, number, status) values(104, 'Keks', 4, 0);
insert into mysteryword (card_id, word, number, status) values(104, 'Croissant', 5, 0);
insert into mysteryword (card_id, word, number, status) values(105, 'Geist', 1, 0);
insert into mysteryword (card_id, word, number, status) values(105, 'Stroh', 2, 0);
insert into mysteryword (card_id, word, number, status) values(105, 'Nagel', 3, 0);
insert into mysteryword (card_id, word, number, status) values(105, 'Potter', 4, 0);
insert into mysteryword (card_id, word, number, status) values(105, 'Darwin', 5, 0);
insert into mysteryword (card_id, word, number, status) values(106, 'Tomate', 1, 0);
insert into mysteryword (card_id, word, number, status) values(106, 'Fallschirm', 2, 0);
insert into mysteryword (card_id, word, number, status) values(106, 'Kanone', 3, 0);
insert into mysteryword (card_id, word, number, status) values(106, 'Fernglas', 4, 0);
insert into mysteryword (card_id, word, number, status) values(106, 'Fata Morgana', 5, 0);
insert into mysteryword (card_id, word, number, status) values(107, 'Ramses', 1, 0);
insert into mysteryword (card_id, word, number, status) values(107, 'Feuer', 2, 0);
insert into mysteryword (card_id, word, number, status) values(107, 'Kreuzung', 3, 0);
insert into mysteryword (card_id, word, number, status) values(107, 'Prinzessin', 4, 0);
insert into mysteryword (card_id, word, number, status) values(107, 'Raumschiff', 5, 0);
insert into mysteryword (card_id, word, number, status) values(108, 'Bowling', 1, 0);
insert into mysteryword (card_id, word, number, status) values(108, 'Churchill', 2, 0);
insert into mysteryword (card_id, word, number, status) values(108, 'Widder', 3, 0);
insert into mysteryword (card_id, word, number, status) values(108, 'Spion', 4, 0);
insert into mysteryword (card_id, word, number, status) values(108, 'Olympiade', 5, 0);
insert into mysteryword (card_id, word, number, status) values(109, 'Klettern', 1, 0);
insert into mysteryword (card_id, word, number, status) values(109, 'Anwalt', 2, 0);
insert into mysteryword (card_id, word, number, status) values(109, 'Tolkien', 3, 0);
insert into mysteryword (card_id, word, number, status) values(109, 'Fluss', 4, 0);
insert into mysteryword (card_id, word, number, status) values(109, 'Teppich', 5, 0);
insert into mysteryword (card_id, word, number, status) values(110, 'Pony', 1, 0);
insert into mysteryword (card_id, word, number, status) values(110, 'Krone', 2, 0);
insert into mysteryword (card_id, word, number, status) values(110, 'Neu', 3, 0);
insert into mysteryword (card_id, word, number, status) values(110, 'Tarantino', 4, 0);
insert into mysteryword (card_id, word, number, status) values(110, 'Heino', 5, 0);
insert into mysteryword (card_id, word, number, status) values(111, 'Ninja', 1, 0);
insert into mysteryword (card_id, word, number, status) values(111, 'Bettdecke', 2, 0);
insert into mysteryword (card_id, word, number, status) values(111, 'Jäger', 3, 0);
insert into mysteryword (card_id, word, number, status) values(111, 'Gemüse', 4, 0);
insert into mysteryword (card_id, word, number, status) values(111, 'Höhle', 5, 0);
insert into mysteryword (card_id, word, number, status) values(112, 'Hans', 1, 0);
insert into mysteryword (card_id, word, number, status) values(112, 'Casino', 2, 0);
insert into mysteryword (card_id, word, number, status) values(112, 'Bonbon', 3, 0);
insert into mysteryword (card_id, word, number, status) values(112, 'Brunnen', 4, 0);
insert into mysteryword (card_id, word, number, status) values(112, 'Licht', 5, 0);
insert into mysteryword (card_id, word, number, status) values(113, 'Sofa', 1, 0);
insert into mysteryword (card_id, word, number, status) values(113, 'Mozart', 2, 0);
insert into mysteryword (card_id, word, number, status) values(113, 'Ring', 3, 0);
insert into mysteryword (card_id, word, number, status) values(113, 'Pizza', 4, 0);
insert into mysteryword (card_id, word, number, status) values(113, 'Bild', 5, 0);
insert into mysteryword (card_id, word, number, status) values(114, 'Feuerwehr', 1, 0);
insert into mysteryword (card_id, word, number, status) values(114, 'Glas', 2, 0);
insert into mysteryword (card_id, word, number, status) values(114, 'Kloss', 3, 0);
insert into mysteryword (card_id, word, number, status) values(114, 'Griechenland', 4, 0);
insert into mysteryword (card_id, word, number, status) values(114, 'Tradition', 5, 0);
insert into mysteryword (card_id, word, number, status) values(115, 'Schlange', 1, 0);
insert into mysteryword (card_id, word, number, status) values(115, 'Pokal', 2, 0);
insert into mysteryword (card_id, word, number, status) values(115, 'Picasso', 3, 0);
insert into mysteryword (card_id, word, number, status) values(115, 'Uhr', 4, 0);
insert into mysteryword (card_id, word, number, status) values(115, 'Scheiterhaufen', 5, 0);
insert into mysteryword (card_id, word, number, status) values(116, 'Zauberer', 1, 0);
insert into mysteryword (card_id, word, number, status) values(116, 'Hockey', 2, 0);
insert into mysteryword (card_id, word, number, status) values(116, 'Banane', 3, 0);
insert into mysteryword (card_id, word, number, status) values(116, 'Helene', 4, 0);
insert into mysteryword (card_id, word, number, status) values(116, 'Caesar', 5, 0);
insert into mysteryword (card_id, word, number, status) values(117, 'Nudel', 1, 0);
insert into mysteryword (card_id, word, number, status) values(117, 'Hut', 2, 0);
insert into mysteryword (card_id, word, number, status) values(117, 'Zahnarzt', 3, 0);
insert into mysteryword (card_id, word, number, status) values(117, 'Weizen', 4, 0);
insert into mysteryword (card_id, word, number, status) values(117, 'Muschel', 5, 0);
insert into mysteryword (card_id, word, number, status) values(118, 'Shakespeare', 1, 0);
insert into mysteryword (card_id, word, number, status) values(118, 'Riese', 2, 0);
insert into mysteryword (card_id, word, number, status) values(118, 'Schaum', 3, 0);
insert into mysteryword (card_id, word, number, status) values(118, 'Keller', 4, 0);
insert into mysteryword (card_id, word, number, status) values(118, 'Messer', 5, 0);
insert into mysteryword (card_id, word, number, status) values(119, 'Kissen', 1, 0);
insert into mysteryword (card_id, word, number, status) values(119, 'Armstrong', 2, 0);
insert into mysteryword (card_id, word, number, status) values(119, 'Schwert', 3, 0);
insert into mysteryword (card_id, word, number, status) values(119, 'Flug', 4, 0);
insert into mysteryword (card_id, word, number, status) values(119, 'Ticket', 5, 0);
insert into mysteryword (card_id, word, number, status) values(120, 'Pinguin', 1, 0);
insert into mysteryword (card_id, word, number, status) values(120, 'Zelle', 2, 0);
insert into mysteryword (card_id, word, number, status) values(120, 'Gandhi', 3, 0);
insert into mysteryword (card_id, word, number, status) values(120, 'Oase', 4, 0);
insert into mysteryword (card_id, word, number, status) values(120, 'Krokodil', 5, 0);
insert into mysteryword (card_id, word, number, status) values(121, 'Schmuck', 1, 0);
insert into mysteryword (card_id, word, number, status) values(121, 'U-Bahn', 2, 0);
insert into mysteryword (card_id, word, number, status) values(121, 'Brille', 3, 0);
insert into mysteryword (card_id, word, number, status) values(121, 'Falco', 4, 0);
insert into mysteryword (card_id, word, number, status) values(121, 'Jackson', 5, 0);
insert into mysteryword (card_id, word, number, status) values(122, 'Zigarette', 1, 0);
insert into mysteryword (card_id, word, number, status) values(122, 'Armband', 2, 0);
insert into mysteryword (card_id, word, number, status) values(122, 'Wetterbericht', 3, 0);
insert into mysteryword (card_id, word, number, status) values(122, 'Turm', 4, 0);
insert into mysteryword (card_id, word, number, status) values(122, 'Tattoo', 5, 0);
insert into mysteryword (card_id, word, number, status) values(123, 'Spielberg', 1, 0);
insert into mysteryword (card_id, word, number, status) values(123, 'Apfel', 2, 0);
insert into mysteryword (card_id, word, number, status) values(123, 'Meerjungfrau', 3, 0);
insert into mysteryword (card_id, word, number, status) values(123, 'Boxen', 4, 0);
insert into mysteryword (card_id, word, number, status) values(123, 'Zwerg', 5, 0);
insert into mysteryword (card_id, word, number, status) values(124, 'Zirkus', 1, 0);
insert into mysteryword (card_id, word, number, status) values(124, 'Elvis', 2, 0);
insert into mysteryword (card_id, word, number, status) values(124, 'Rasenmäher', 3, 0);
insert into mysteryword (card_id, word, number, status) values(124, 'Stein', 4, 0);
insert into mysteryword (card_id, word, number, status) values(124, 'Zug', 5, 0);
insert into mysteryword (card_id, word, number, status) values(125, 'Sardine', 1, 0);
insert into mysteryword (card_id, word, number, status) values(125, 'Stück', 2, 0);
insert into mysteryword (card_id, word, number, status) values(125, 'Kleopatra', 3, 0);
insert into mysteryword (card_id, word, number, status) values(125, 'Fenster', 4, 0);
insert into mysteryword (card_id, word, number, status) values(125, 'Granatapfel', 5, 0);
insert into mysteryword (card_id, word, number, status) values(126, 'Füllung', 1, 0);
insert into mysteryword (card_id, word, number, status) values(126, 'Bürste', 2, 0);
insert into mysteryword (card_id, word, number, status) values(126, 'Schwein', 3, 0);
insert into mysteryword (card_id, word, number, status) values(126, 'Avicii', 4, 0);
insert into mysteryword (card_id, word, number, status) values(126, 'Hausschuh', 5, 0);
insert into mysteryword (card_id, word, number, status) values(127, 'Blatt', 1, 0);
insert into mysteryword (card_id, word, number, status) values(127, 'Puma', 2, 0);
insert into mysteryword (card_id, word, number, status) values(127, 'Revolution', 3, 0);
insert into mysteryword (card_id, word, number, status) values(127, 'Sahara', 4, 0);
insert into mysteryword (card_id, word, number, status) values(127, 'Ritter', 5, 0);
insert into mysteryword (card_id, word, number, status) values(128, 'Frieden', 1, 0);
insert into mysteryword (card_id, word, number, status) values(128, 'Blume', 2, 0);
insert into mysteryword (card_id, word, number, status) values(128, 'Schweiz', 3, 0);
insert into mysteryword (card_id, word, number, status) values(128, 'Kalender', 4, 0);
insert into mysteryword (card_id, word, number, status) values(128, 'Schnitzel', 5, 0);
insert into mysteryword (card_id, word, number, status) values(129, 'Kanada', 1, 0);
insert into mysteryword (card_id, word, number, status) values(129, 'Zoo', 2, 0);
insert into mysteryword (card_id, word, number, status) values(129, 'Pfeife', 3, 0);
insert into mysteryword (card_id, word, number, status) values(129, 'Buch', 4, 0);
insert into mysteryword (card_id, word, number, status) values(129, 'Meerrettich', 5, 0);

/* English words*/

insert into card(id, drawn, language) values(20, false, 1);
insert into card(id, drawn, language) values(21, false, 1);
insert into card(id, drawn, language) values(22, false, 1);
insert into card(id, drawn, language) values(23, false, 1);
insert into card(id, drawn, language) values(24, false, 1);
insert into card(id, drawn, language) values(25, false, 1);
insert into card(id, drawn, language) values(26, false, 1);
insert into card(id, drawn, language) values(27, false, 1);
insert into card(id, drawn, language) values(28, false, 1);
insert into card(id, drawn, language) values(29, false, 1);
insert into card(id, drawn, language) values(30, false, 1);
insert into card(id, drawn, language) values(31, false, 1);
insert into card(id, drawn, language) values(32, false, 1);
insert into card(id, drawn, language) values(33, false, 1);
insert into card(id, drawn, language) values(34, false, 1);
insert into card(id, drawn, language) values(35, false, 1);
insert into card(id, drawn, language) values(36, false, 1);
insert into card(id, drawn, language) values(37, false, 1);
insert into card(id, drawn, language) values(38, false, 1);
insert into card(id, drawn, language) values(39, false, 1);
insert into card(id, drawn, language) values(40, false, 1);
insert into card(id, drawn, language) values(41, false, 1);
insert into card(id, drawn, language) values(42, false, 1);
insert into card(id, drawn, language) values(43, false, 1);
insert into card(id, drawn, language) values(44, false, 1);
insert into card(id, drawn, language) values(45, false, 1);
insert into card(id, drawn, language) values(46, false, 1);
insert into card(id, drawn, language) values(47, false, 1);
insert into card(id, drawn, language) values(48, false, 1);
insert into card(id, drawn, language) values(49, false, 1);
insert into card(id, drawn, language) values(50, false, 1);
insert into card(id, drawn, language) values(51, false, 1);
insert into card(id, drawn, language) values(52, false, 1);
insert into card(id, drawn, language) values(53, false, 1);
insert into card(id, drawn, language) values(54, false, 1);
insert into card(id, drawn, language) values(55, false, 1);
insert into card(id, drawn, language) values(56, false, 1);
insert into card(id, drawn, language) values(57, false, 1);
insert into card(id, drawn, language) values(58, false, 1);
insert into card(id, drawn, language) values(59, false, 1);
insert into card(id, drawn, language) values(60, false, 1);
insert into card(id, drawn, language) values(61, false, 1);
insert into card(id, drawn, language) values(62, false, 1);
insert into card(id, drawn, language) values(63, false, 1);
insert into card(id, drawn, language) values(64, false, 1);
insert into card(id, drawn, language) values(65, false, 1);
insert into card(id, drawn, language) values(66, false, 1);
insert into card(id, drawn, language) values(67, false, 1);
insert into card(id, drawn, language) values(68, false, 1);
insert into card(id, drawn, language) values(69, false, 1);
insert into card(id, drawn, language) values(70, false, 1);
insert into card(id, drawn, language) values(71, false, 1);
insert into card(id, drawn, language) values(72, false, 1);
insert into card(id, drawn, language) values(73, false, 1);
insert into card(id, drawn, language) values(74, false, 1);



insert into mysteryword (card_id, word, number, status) values(20, 'Alcatraz', 1, 0);
insert into mysteryword (card_id, word, number, status) values(20, 'Smoke', 2, 0);
insert into mysteryword (card_id, word, number, status) values(20, 'Hazelnut', 3, 0);
insert into mysteryword (card_id, word, number, status) values(20, 'Diamond', 4, 0);
insert into mysteryword (card_id, word, number, status) values(20, 'Rose', 5, 0);
insert into mysteryword (card_id, word, number, status) values(21, 'Puppet', 1, 0);
insert into mysteryword (card_id, word, number, status) values(21, 'Game', 2, 0);
insert into mysteryword (card_id, word, number, status) values(21, 'Vegas', 3, 0);
insert into mysteryword (card_id, word, number, status) values(21, 'Chest', 4, 0);
insert into mysteryword (card_id, word, number, status) values(21, 'Airplane', 5, 0);
insert into mysteryword (card_id, word, number, status) values(22, 'Cord', 1, 0);
insert into mysteryword (card_id, word, number, status) values(22, 'Australia', 2, 0);
insert into mysteryword (card_id, word, number, status) values(22, 'Castle', 3, 0);
insert into mysteryword (card_id, word, number, status) values(22, 'Guard', 4, 0);
insert into mysteryword (card_id, word, number, status) values(22, 'Sheep', 5, 0);
insert into mysteryword (card_id, word, number, status) values(23, 'Fleece', 1, 0);
insert into mysteryword (card_id, word, number, status) values(23, 'Mouse', 2, 0);
insert into mysteryword (card_id, word, number, status) values(23, 'Chain', 3, 0);
insert into mysteryword (card_id, word, number, status) values(23, 'Farm', 4, 0);
insert into mysteryword (card_id, word, number, status) values(23, 'Belgium', 5, 0);
insert into mysteryword (card_id, word, number, status) values(24, 'Pepper', 1, 0);
insert into mysteryword (card_id, word, number, status) values(24, 'Triangle', 2, 0);
insert into mysteryword (card_id, word, number, status) values(24, 'Doll', 3, 0);
insert into mysteryword (card_id, word, number, status) values(24, 'Italy', 4, 0);
insert into mysteryword (card_id, word, number, status) values(24, 'Stage', 5, 0);
insert into mysteryword (card_id, word, number, status) values(25, 'Heart', 1, 0);
insert into mysteryword (card_id, word, number, status) values(25, 'Moscow', 2, 0);
insert into mysteryword (card_id, word, number, status) values(25, 'Billiards', 3, 0);
insert into mysteryword (card_id, word, number, status) values(25, 'Unicorn', 4, 0);
insert into mysteryword (card_id, word, number, status) values(25, 'Orange', 5, 0);
insert into mysteryword (card_id, word, number, status) values(26, 'Tokyo', 1, 0);
insert into mysteryword (card_id, word, number, status) values(26, 'Heel', 2, 0);
insert into mysteryword (card_id, word, number, status) values(26, 'Chicken', 3, 0);
insert into mysteryword (card_id, word, number, status) values(26, 'Helicopter', 4, 0);
insert into mysteryword (card_id, word, number, status) values(26, 'Officer', 5, 0);
insert into mysteryword (card_id, word, number, status) values(27, 'Melon', 1, 0);
insert into mysteryword (card_id, word, number, status) values(27, 'Anchor', 2, 0);
insert into mysteryword (card_id, word, number, status) values(27, 'Israel', 3, 0);
insert into mysteryword (card_id, word, number, status) values(27, 'Cactus', 4, 0);
insert into mysteryword (card_id, word, number, status) values(27, 'Tennis', 5, 0);
insert into mysteryword (card_id, word, number, status) values(28, 'France', 1, 0);
insert into mysteryword (card_id, word, number, status) values(28, 'Moon', 2, 0);
insert into mysteryword (card_id, word, number, status) values(28, 'Canteen', 3, 0);
insert into mysteryword (card_id, word, number, status) values(28, 'Emperor penguin', 4, 0);
insert into mysteryword (card_id, word, number, status) values(28, 'Tool', 5, 0);
insert into mysteryword (card_id, word, number, status) values(29, 'Brain', 1, 0);
insert into mysteryword (card_id, word, number, status) values(29, 'Mask', 2, 0);
insert into mysteryword (card_id, word, number, status) values(29, 'Concert', 3, 0);
insert into mysteryword (card_id, word, number, status) values(29, 'Troy', 4, 0);
insert into mysteryword (card_id, word, number, status) values(29, 'Shark', 5, 0);
insert into mysteryword (card_id, word, number, status) values(30, 'Music', 1, 0);
insert into mysteryword (card_id, word, number, status) values(30, 'Neck', 2, 0);
insert into mysteryword (card_id, word, number, status) values(30, 'America', 3, 0);
insert into mysteryword (card_id, word, number, status) values(30, 'Coffee', 4, 0);
insert into mysteryword (card_id, word, number, status) values(30, 'Fever', 5, 0);
insert into mysteryword (card_id, word, number, status) values(31, 'Barbie', 1, 0);
insert into mysteryword (card_id, word, number, status) values(31, 'Chocolate', 2, 0);
insert into mysteryword (card_id, word, number, status) values(31, 'Snow', 3, 0);
insert into mysteryword (card_id, word, number, status) values(31, 'Tie', 4, 0);
insert into mysteryword (card_id, word, number, status) values(31, 'Wind', 5, 0);
insert into mysteryword (card_id, word, number, status) values(32, 'Thought', 1, 0);
insert into mysteryword (card_id, word, number, status) values(32, 'Frankenstein', 2, 0);
insert into mysteryword (card_id, word, number, status) values(32, 'Beam', 3, 0);
insert into mysteryword (card_id, word, number, status) values(32, 'Accent', 4, 0);
insert into mysteryword (card_id, word, number, status) values(32, 'Shower', 5, 0);
insert into mysteryword (card_id, word, number, status) values(33, 'Ladybird', 1, 0);
insert into mysteryword (card_id, word, number, status) values(33, 'Mustard', 2, 0);
insert into mysteryword (card_id, word, number, status) values(33, 'Sherlock', 3, 0);
insert into mysteryword (card_id, word, number, status) values(33, 'Bottle', 4, 0);
insert into mysteryword (card_id, word, number, status) values(33, 'Virus', 5, 0);
insert into mysteryword (card_id, word, number, status) values(34, 'Poison', 1, 0);
insert into mysteryword (card_id, word, number, status) values(34, 'Star', 2, 0);
insert into mysteryword (card_id, word, number, status) values(34, 'Wolf', 3, 0);
insert into mysteryword (card_id, word, number, status) values(34, 'Lena', 4, 0);
insert into mysteryword (card_id, word, number, status) values(34, 'Birthday', 5, 0);
insert into mysteryword (card_id, word, number, status) values(35, 'Baker', 1, 0);
insert into mysteryword (card_id, word, number, status) values(35, 'Perfume', 2, 0);
insert into mysteryword (card_id, word, number, status) values(35, 'Flame', 3, 0);
insert into mysteryword (card_id, word, number, status) values(35, 'Zombie', 4, 0);
insert into mysteryword (card_id, word, number, status) values(35, 'Joker', 5, 0);
insert into mysteryword (card_id, word, number, status) values(36, 'Buffy', 1, 0);
insert into mysteryword (card_id, word, number, status) values(36, 'Volcano', 2, 0);
insert into mysteryword (card_id, word, number, status) values(36, 'Passion', 3, 0);
insert into mysteryword (card_id, word, number, status) values(36, 'Cock', 4, 0);
insert into mysteryword (card_id, word, number, status) values(36, 'Electricity', 5, 0);
insert into mysteryword (card_id, word, number, status) values(37, 'Genius', 1, 0);
insert into mysteryword (card_id, word, number, status) values(37, 'Dracula', 2, 0);
insert into mysteryword (card_id, word, number, status) values(37, 'Lion', 3, 0);
insert into mysteryword (card_id, word, number, status) values(37, 'Sock', 4, 0);
insert into mysteryword (card_id, word, number, status) values(37, 'Friday', 5, 0);
insert into mysteryword (card_id, word, number, status) values(38, 'Pirate', 1, 0);
insert into mysteryword (card_id, word, number, status) values(38, 'Holidays', 2, 0);
insert into mysteryword (card_id, word, number, status) values(38, 'Fairy', 3, 0);
insert into mysteryword (card_id, word, number, status) values(38, 'Magnet', 4, 0);
insert into mysteryword (card_id, word, number, status) values(38, 'Fork', 5, 0);
insert into mysteryword (card_id, word, number, status) values(39, 'Syrup', 1, 0);
insert into mysteryword (card_id, word, number, status) values(39, 'Forest', 2, 0);
insert into mysteryword (card_id, word, number, status) values(39, 'Scale', 3, 0);
insert into mysteryword (card_id, word, number, status) values(39, 'Zeus', 4, 0);
insert into mysteryword (card_id, word, number, status) values(39, 'Cockroach', 5, 0);
insert into mysteryword (card_id, word, number, status) values(40, 'Dinosaur', 1, 0);
insert into mysteryword (card_id, word, number, status) values(40, 'Yellow', 2, 0);
insert into mysteryword (card_id, word, number, status) values(40, 'Mushroom', 3, 0);
insert into mysteryword (card_id, word, number, status) values(40, 'Pigeon', 4, 0);
insert into mysteryword (card_id, word, number, status) values(40, 'Pikachu', 5, 0);
insert into mysteryword (card_id, word, number, status) values(41, 'Asterix', 1, 0);
insert into mysteryword (card_id, word, number, status) values(41, 'Robots', 2, 0);
insert into mysteryword (card_id, word, number, status) values(41, 'Comedy', 3, 0);
insert into mysteryword (card_id, word, number, status) values(41, 'Language', 4, 0);
insert into mysteryword (card_id, word, number, status) values(41, 'Hairdresser', 5, 0);
insert into mysteryword (card_id, word, number, status) values(42, 'Cocktail', 1, 0);
insert into mysteryword (card_id, word, number, status) values(42, 'Mario', 2, 0);
insert into mysteryword (card_id, word, number, status) values(42, 'Cork', 3, 0);
insert into mysteryword (card_id, word, number, status) values(42, 'Violin', 4, 0);
insert into mysteryword (card_id, word, number, status) values(42, 'Peach', 5, 0);
insert into mysteryword (card_id, word, number, status) values(43, 'Fox', 1, 0);
insert into mysteryword (card_id, word, number, status) values(43, 'Police', 2, 0);
insert into mysteryword (card_id, word, number, status) values(43, 'Simpson', 3, 0);
insert into mysteryword (card_id, word, number, status) values(43, 'Donut', 4, 0);
insert into mysteryword (card_id, word, number, status) values(43, 'Newspaper', 5, 0);
insert into mysteryword (card_id, word, number, status) values(44, 'Mountains', 1, 0);
insert into mysteryword (card_id, word, number, status) values(44, 'Peanut', 2, 0);
insert into mysteryword (card_id, word, number, status) values(44, 'Light bulb', 3, 0);
insert into mysteryword (card_id, word, number, status) values(44, 'Jedi', 4, 0);
insert into mysteryword (card_id, word, number, status) values(44, 'Chili', 5, 0);
insert into mysteryword (card_id, word, number, status) values(45, 'Sombrero', 1, 0);
insert into mysteryword (card_id, word, number, status) values(45, 'Cloverleaf', 2, 0);
insert into mysteryword (card_id, word, number, status) values(45, 'Button', 3, 0);
insert into mysteryword (card_id, word, number, status) values(45, 'Cheese', 4, 0);
insert into mysteryword (card_id, word, number, status) values(45, 'Chewbacca', 5, 0);
insert into mysteryword (card_id, word, number, status) values(46, 'Revolver', 1, 0);
insert into mysteryword (card_id, word, number, status) values(46, 'Doctor', 2, 0);
insert into mysteryword (card_id, word, number, status) values(46, 'Strawberry', 3, 0);
insert into mysteryword (card_id, word, number, status) values(46, 'Nuclear power', 4, 0);
insert into mysteryword (card_id, word, number, status) values(46, 'Lottery', 5, 0);
insert into mysteryword (card_id, word, number, status) values(47, 'Cemetery', 1, 0);
insert into mysteryword (card_id, word, number, status) values(47, 'Cupid', 2, 0);
insert into mysteryword (card_id, word, number, status) values(47, 'Umbrella', 3, 0);
insert into mysteryword (card_id, word, number, status) values(47, 'Jump', 4, 0);
insert into mysteryword (card_id, word, number, status) values(47, 'Root', 5, 0);
insert into mysteryword (card_id, word, number, status) values(48, 'Treasure', 1, 0);
insert into mysteryword (card_id, word, number, status) values(48, 'Pilot', 2, 0);
insert into mysteryword (card_id, word, number, status) values(48, 'Mickey', 3, 0);
insert into mysteryword (card_id, word, number, status) values(48, 'Sewerage', 4, 0);
insert into mysteryword (card_id, word, number, status) values(48, 'Galaxy', 5, 0);
insert into mysteryword (card_id, word, number, status) values(49, 'Moustache', 1, 0);
insert into mysteryword (card_id, word, number, status) values(49, 'Bubble', 2, 0);
insert into mysteryword (card_id, word, number, status) values(49, 'Chain', 3, 0);
insert into mysteryword (card_id, word, number, status) values(49, 'Strong', 4, 0);
insert into mysteryword (card_id, word, number, status) values(49, 'Cookie', 5, 0);
insert into mysteryword (card_id, word, number, status) values(50, 'Croissant', 1, 0);
insert into mysteryword (card_id, word, number, status) values(50, 'Spirit', 2, 0);
insert into mysteryword (card_id, word, number, status) values(50, 'Straw', 3, 0);
insert into mysteryword (card_id, word, number, status) values(50, 'Nail', 4, 0);
insert into mysteryword (card_id, word, number, status) values(50, 'Potter', 5, 0);
insert into mysteryword (card_id, word, number, status) values(51, 'Darwin', 1, 0);
insert into mysteryword (card_id, word, number, status) values(51, 'Tomato', 2, 0);
insert into mysteryword (card_id, word, number, status) values(51, 'Parachute', 3, 0);
insert into mysteryword (card_id, word, number, status) values(51, 'Cannon', 4, 0);
insert into mysteryword (card_id, word, number, status) values(51, 'Binoculars', 5, 0);
insert into mysteryword (card_id, word, number, status) values(52, 'Fata morgana', 1, 0);
insert into mysteryword (card_id, word, number, status) values(52, 'Ramses', 2, 0);
insert into mysteryword (card_id, word, number, status) values(52, 'Fire', 3, 0);
insert into mysteryword (card_id, word, number, status) values(52, 'Intersection', 4, 0);
insert into mysteryword (card_id, word, number, status) values(52, 'Princess', 5, 0);
insert into mysteryword (card_id, word, number, status) values(53, 'Spaceship', 1, 0);
insert into mysteryword (card_id, word, number, status) values(53, 'Bowling', 2, 0);
insert into mysteryword (card_id, word, number, status) values(53, 'Churchill', 3, 0);
insert into mysteryword (card_id, word, number, status) values(53, 'Aries', 4, 0);
insert into mysteryword (card_id, word, number, status) values(53, 'Spy', 5, 0);
insert into mysteryword (card_id, word, number, status) values(54, 'Olympics', 1, 0);
insert into mysteryword (card_id, word, number, status) values(54, 'Climbing', 2, 0);
insert into mysteryword (card_id, word, number, status) values(54, 'Lawyer', 3, 0);
insert into mysteryword (card_id, word, number, status) values(54, 'Tolkien', 4, 0);
insert into mysteryword (card_id, word, number, status) values(54, 'River', 5, 0);
insert into mysteryword (card_id, word, number, status) values(55, 'Carpet', 1, 0);
insert into mysteryword (card_id, word, number, status) values(55, 'Pony', 2, 0);
insert into mysteryword (card_id, word, number, status) values(55, 'Crown', 3, 0);
insert into mysteryword (card_id, word, number, status) values(55, 'New', 4, 0);
insert into mysteryword (card_id, word, number, status) values(55, 'Tarantino', 5, 0);
insert into mysteryword (card_id, word, number, status) values(56, 'Heino', 1, 0);
insert into mysteryword (card_id, word, number, status) values(56, 'Ninja', 2, 0);
insert into mysteryword (card_id, word, number, status) values(56, 'Duvet', 3, 0);
insert into mysteryword (card_id, word, number, status) values(56, 'Hunter', 4, 0);
insert into mysteryword (card_id, word, number, status) values(56, 'Vegetables', 5, 0);
insert into mysteryword (card_id, word, number, status) values(57, 'Cave', 1, 0);
insert into mysteryword (card_id, word, number, status) values(57, 'Hans', 2, 0);
insert into mysteryword (card_id, word, number, status) values(57, 'Casino', 3, 0);
insert into mysteryword (card_id, word, number, status) values(57, 'Candy', 4, 0);
insert into mysteryword (card_id, word, number, status) values(57, 'Fountain', 5, 0);
insert into mysteryword (card_id, word, number, status) values(58, 'Light', 1, 0);
insert into mysteryword (card_id, word, number, status) values(58, 'Sofa', 2, 0);
insert into mysteryword (card_id, word, number, status) values(58, 'Mozart', 3, 0);
insert into mysteryword (card_id, word, number, status) values(58, 'Ring', 4, 0);
insert into mysteryword (card_id, word, number, status) values(58, 'Pizza', 5, 0);
insert into mysteryword (card_id, word, number, status) values(59, 'Picture', 1, 0);
insert into mysteryword (card_id, word, number, status) values(59, 'Fire department', 2, 0);
insert into mysteryword (card_id, word, number, status) values(59, 'Glass', 3, 0);
insert into mysteryword (card_id, word, number, status) values(59, 'Meatball', 4, 0);
insert into mysteryword (card_id, word, number, status) values(59, 'Greece', 5, 0);
insert into mysteryword (card_id, word, number, status) values(60, 'Tradition', 1, 0);
insert into mysteryword (card_id, word, number, status) values(60, 'Snake', 2, 0);
insert into mysteryword (card_id, word, number, status) values(60, 'Trophy', 3, 0);
insert into mysteryword (card_id, word, number, status) values(60, 'Picasso', 4, 0);
insert into mysteryword (card_id, word, number, status) values(60, 'Clock', 5, 0);
insert into mysteryword (card_id, word, number, status) values(61, 'Pyre', 1, 0);
insert into mysteryword (card_id, word, number, status) values(61, 'Wizard', 2, 0);
insert into mysteryword (card_id, word, number, status) values(61, 'Hockey', 3, 0);
insert into mysteryword (card_id, word, number, status) values(61, 'Banana', 4, 0);
insert into mysteryword (card_id, word, number, status) values(61, 'Helene', 5, 0);
insert into mysteryword (card_id, word, number, status) values(62, 'Caesar', 1, 0);
insert into mysteryword (card_id, word, number, status) values(62, 'Noodle', 2, 0);
insert into mysteryword (card_id, word, number, status) values(62, 'Hat', 3, 0);
insert into mysteryword (card_id, word, number, status) values(62, 'Dentist', 4, 0);
insert into mysteryword (card_id, word, number, status) values(62, 'Wheat', 5, 0);
insert into mysteryword (card_id, word, number, status) values(63, 'Mussel', 1, 0);
insert into mysteryword (card_id, word, number, status) values(63, 'Shakespeare', 2, 0);
insert into mysteryword (card_id, word, number, status) values(63, 'Giant', 3, 0);
insert into mysteryword (card_id, word, number, status) values(63, 'Foam', 4, 0);
insert into mysteryword (card_id, word, number, status) values(63, 'Cellar', 5, 0);
insert into mysteryword (card_id, word, number, status) values(64, 'Knives', 1, 0);
insert into mysteryword (card_id, word, number, status) values(64, 'Pillows', 2, 0);
insert into mysteryword (card_id, word, number, status) values(64, 'Armstrong', 3, 0);
insert into mysteryword (card_id, word, number, status) values(64, 'Sword', 4, 0);
insert into mysteryword (card_id, word, number, status) values(64, 'Flight', 5, 0);
insert into mysteryword (card_id, word, number, status) values(65, 'Ticket', 1, 0);
insert into mysteryword (card_id, word, number, status) values(65, 'Penguin', 2, 0);
insert into mysteryword (card_id, word, number, status) values(65, 'Cell', 3, 0);
insert into mysteryword (card_id, word, number, status) values(65, 'Gandhi', 4, 0);
insert into mysteryword (card_id, word, number, status) values(65, 'Oasis', 5, 0);
insert into mysteryword (card_id, word, number, status) values(66, 'Crocodile', 1, 0);
insert into mysteryword (card_id, word, number, status) values(66, 'Jewellery', 2, 0);
insert into mysteryword (card_id, word, number, status) values(66, 'Subway', 3, 0);
insert into mysteryword (card_id, word, number, status) values(66, 'Glasses', 4, 0);
insert into mysteryword (card_id, word, number, status) values(66, 'Falco', 5, 0);
insert into mysteryword (card_id, word, number, status) values(67, 'Jackson', 1, 0);
insert into mysteryword (card_id, word, number, status) values(67, 'Cigarette', 2, 0);
insert into mysteryword (card_id, word, number, status) values(67, 'Bracelet', 3, 0);
insert into mysteryword (card_id, word, number, status) values(67, 'Weather forecast', 4, 0);
insert into mysteryword (card_id, word, number, status) values(67, 'Tower', 5, 0);
insert into mysteryword (card_id, word, number, status) values(68, 'Tattoo', 1, 0);
insert into mysteryword (card_id, word, number, status) values(68, 'Spielberg', 2, 0);
insert into mysteryword (card_id, word, number, status) values(68, 'Apple', 3, 0);
insert into mysteryword (card_id, word, number, status) values(68, 'Mermaid', 4, 0);
insert into mysteryword (card_id, word, number, status) values(68, 'Boxes', 5, 0);
insert into mysteryword (card_id, word, number, status) values(69, 'Dwarf', 1, 0);
insert into mysteryword (card_id, word, number, status) values(69, 'Circus', 2, 0);
insert into mysteryword (card_id, word, number, status) values(69, 'Elvis', 3, 0);
insert into mysteryword (card_id, word, number, status) values(69, 'Lawn mower', 4, 0);
insert into mysteryword (card_id, word, number, status) values(69, 'Stone', 5, 0);
insert into mysteryword (card_id, word, number, status) values(70, 'Train', 1, 0);
insert into mysteryword (card_id, word, number, status) values(70, 'Sardine', 2, 0);
insert into mysteryword (card_id, word, number, status) values(70, 'Piece', 3, 0);
insert into mysteryword (card_id, word, number, status) values(70, 'Cleopatra', 4, 0);
insert into mysteryword (card_id, word, number, status) values(70, 'Window', 5, 0);
insert into mysteryword (card_id, word, number, status) values(71, 'Pomegranate', 1, 0);
insert into mysteryword (card_id, word, number, status) values(71, 'Filling', 2, 0);
insert into mysteryword (card_id, word, number, status) values(71, 'Brush', 3, 0);
insert into mysteryword (card_id, word, number, status) values(71, 'Pig', 4, 0);
insert into mysteryword (card_id, word, number, status) values(71, 'Avicii', 5, 0);
insert into mysteryword (card_id, word, number, status) values(72, 'Slipper', 1, 0);
insert into mysteryword (card_id, word, number, status) values(72, 'Sheet', 2, 0);
insert into mysteryword (card_id, word, number, status) values(72, 'Puma', 3, 0);
insert into mysteryword (card_id, word, number, status) values(72, 'Revolution', 4, 0);
insert into mysteryword (card_id, word, number, status) values(72, 'Sahara', 5, 0);
insert into mysteryword (card_id, word, number, status) values(73, 'Knight', 1, 0);
insert into mysteryword (card_id, word, number, status) values(73, 'Peace', 2, 0);
insert into mysteryword (card_id, word, number, status) values(73, 'Flower', 3, 0);
insert into mysteryword (card_id, word, number, status) values(73, 'Switzerland', 4, 0);
insert into mysteryword (card_id, word, number, status) values(73, 'Calendar', 5, 0);
insert into mysteryword (card_id, word, number, status) values(74, 'Schnitzel', 1, 0);
insert into mysteryword (card_id, word, number, status) values(74, 'Canada', 2, 0);
insert into mysteryword (card_id, word, number, status) values(74, 'Zoo', 3, 0);
insert into mysteryword (card_id, word, number, status) values(74, 'Whistle', 4, 0);
insert into mysteryword (card_id, word, number, status) values(74, 'Book', 5, 0);