insert into card(id, drawn) values(1, false);
insert into card(id, drawn) values(2, false);
insert into card(id, drawn) values(3, false);
insert into card(id, drawn) values(4, false);
insert into card(id, drawn) values(5, false);
insert into card(id, drawn) values(6, false);
insert into card(id, drawn) values(7, false);
insert into card(id, drawn) values(8, false);
insert into card(id, drawn) values(9, false);
insert into card(id, drawn) values(10, false);
insert into card(id, drawn) values(11, false);
insert into card(id, drawn) values(12, false);
insert into card(id, drawn) values(13, false);
insert into card(id, drawn) values(14, false);
insert into card(id, drawn) values(15, false);
insert into card(id, drawn) values(16, false);
insert into card(id, drawn) values(17, false);
insert into card(id, drawn) values(18, false);
insert into card(id, drawn) values(19, false);
/*insert into card(id, drawn) values(20, false);
insert into card(id, drawn) values(21, false);
insert into card(id, drawn) values(22, false);
insert into card(id, drawn) values(23, false);
insert into card(id, drawn) values(24, false);
insert into card(id, drawn) values(25, false);
insert into card(id, drawn) values(26, false);
insert into card(id, drawn) values(27, false);
insert into card(id, drawn) values(28, false);
insert into card(id, drawn) values(29, false);
insert into card(id, drawn) values(30, false);
insert into card(id, drawn) values(31, false);
insert into card(id, drawn) values(32, false);
insert into card(id, drawn) values(33, false);
insert into card(id, drawn) values(34, false);
insert into card(id, drawn) values(35, false);
insert into card(id, drawn) values(36, false);
insert into card(id, drawn) values(37, false);
insert into card(id, drawn) values(38, false);
insert into card(id, drawn) values(39, false);
insert into card(id, drawn) values(40, false);
insert into card(id, drawn) values(41, false);
insert into card(id, drawn) values(42, false);
insert into card(id, drawn) values(43, false);
insert into card(id, drawn) values(44, false);
insert into card(id, drawn) values(45, false);
insert into card(id, drawn) values(46, false);
insert into card(id, drawn) values(47, false);
insert into card(id, drawn) values(48, false);
insert into card(id, drawn) values(49, false);
insert into card(id, drawn) values(50, false);
insert into card(id, drawn) values(51, false);
insert into card(id, drawn) values(52, false);
insert into card(id, drawn) values(53, false);
insert into card(id, drawn) values(54, false);*/

insert into mysteryword (card_id, word, status) values(1, 'Alcatraz', 0);
insert into mysteryword (card_id, word, status) values(1, 'Rauch', 0);
insert into mysteryword (card_id, word, status) values(1, 'Haselnuss', 0);
insert into mysteryword (card_id, word, status) values(1, 'Diamant', 0);
insert into mysteryword (card_id, word, status) values(1, 'Rose', 0);
insert into mysteryword (card_id, word, status) values(2, 'Marionette', 0);
insert into mysteryword (card_id, word, status) values(2, 'Spiel', 0);
insert into mysteryword (card_id, word, status) values(2, 'Vegas', 0);
insert into mysteryword (card_id, word, status) values(2, 'Truhe', 0);
insert into mysteryword (card_id, word, status) values(2, 'Flugzeug', 0);
insert into mysteryword (card_id, word, status) values(3, 'Schnur', 0);
insert into mysteryword (card_id, word, status) values(3, 'Australien', 0);
insert into mysteryword (card_id, word, status) values(3, 'Schloss', 0);
insert into mysteryword (card_id, word, status) values(3, 'Wache', 0);
insert into mysteryword (card_id, word, status) values(3, 'Schaf', 0);
insert into mysteryword (card_id, word, status) values(4, 'Fleece', 0);
insert into mysteryword (card_id, word, status) values(4, 'Maus', 0);
insert into mysteryword (card_id, word, status) values(4, 'Kette', 0);
insert into mysteryword (card_id, word, status) values(4, 'Bauernhof', 0);
insert into mysteryword (card_id, word, status) values(4, 'Belgien', 0);
insert into mysteryword (card_id, word, status) values(5, 'Pfeffer', 0);
insert into mysteryword (card_id, word, status) values(5, 'Dreieck', 0);
insert into mysteryword (card_id, word, status) values(5, 'Puppe', 0);
insert into mysteryword (card_id, word, status) values(5, 'Italien', 0);
insert into mysteryword (card_id, word, status) values(5, 'Bühne', 0);
insert into mysteryword (card_id, word, status) values(6, 'Herz', 0);
insert into mysteryword (card_id, word, status) values(6, 'Moskau', 0);
insert into mysteryword (card_id, word, status) values(6, 'Billard', 0);
insert into mysteryword (card_id, word, status) values(6, 'Einhorn', 0);
insert into mysteryword (card_id, word, status) values(6, 'Orange', 0);
insert into mysteryword (card_id, word, status) values(7, 'Tokio', 0);
insert into mysteryword (card_id, word, status) values(7, 'Ferse', 0);
insert into mysteryword (card_id, word, status) values(7, 'Huhn', 0);
insert into mysteryword (card_id, word, status) values(7, 'Helikopter', 0);
insert into mysteryword (card_id, word, status) values(7, 'Offizier', 0);
insert into mysteryword (card_id, word, status) values(8, 'Melone', 0);
insert into mysteryword (card_id, word, status) values(8, 'Anker', 0);
insert into mysteryword (card_id, word, status) values(8, 'Israel', 0);
insert into mysteryword (card_id, word, status) values(8, 'Kaktus', 0);
insert into mysteryword (card_id, word, status) values(8, 'Tennis', 0);
insert into mysteryword (card_id, word, status) values(9, 'Frankreich', 0);
insert into mysteryword (card_id, word, status) values(9, 'Mond', 0);
insert into mysteryword (card_id, word, status) values(9, 'Kantine', 0);
insert into mysteryword (card_id, word, status) values(9, 'Kaiserpinguin', 0);
insert into mysteryword (card_id, word, status) values(9, 'Werkzeug', 0);
insert into mysteryword (card_id, word, status) values(10, 'Gehirn', 0);
insert into mysteryword (card_id, word, status) values(10, 'Maske', 0);
insert into mysteryword (card_id, word, status) values(10, 'Konzert', 0);
insert into mysteryword (card_id, word, status) values(10, 'Troja', 0);
insert into mysteryword (card_id, word, status) values(10, 'Hai', 0);
insert into mysteryword (card_id, word, status) values(11, 'Musik', 0);
insert into mysteryword (card_id, word, status) values(11, 'Hals', 0);
insert into mysteryword (card_id, word, status) values(11, 'Amerika', 0);
insert into mysteryword (card_id, word, status) values(11, 'Kaffee', 0);
insert into mysteryword (card_id, word, status) values(11, 'Fieber', 0);
insert into mysteryword (card_id, word, status) values(12, 'Barbie', 0);
insert into mysteryword (card_id, word, status) values(12, 'Schokolade', 0);
insert into mysteryword (card_id, word, status) values(12, 'Schnee', 0);
insert into mysteryword (card_id, word, status) values(12, 'Krawatte', 0);
insert into mysteryword (card_id, word, status) values(12, 'Wind', 0);
insert into mysteryword (card_id, word, status) values(13, 'Gedanke', 0);
insert into mysteryword (card_id, word, status) values(13, 'Frankenstein', 0);
insert into mysteryword (card_id, word, status) values(13, 'Strahl', 0);
insert into mysteryword (card_id, word, status) values(13, 'Akzent', 0);
insert into mysteryword (card_id, word, status) values(13, 'Dusche', 0);
insert into mysteryword (card_id, word, status) values(14, 'Marienkäfer', 0);
insert into mysteryword (card_id, word, status) values(14, 'Senf', 0);
insert into mysteryword (card_id, word, status) values(14, 'Sherlock', 0);
insert into mysteryword (card_id, word, status) values(14, 'Flasche', 0);
insert into mysteryword (card_id, word, status) values(14, 'Virus', 0);
insert into mysteryword (card_id, word, status) values(15, 'Gift', 0);
insert into mysteryword (card_id, word, status) values(15, 'Stern', 0);
insert into mysteryword (card_id, word, status) values(15, 'Wolf', 0);
insert into mysteryword (card_id, word, status) values(15, 'Lena', 0);
insert into mysteryword (card_id, word, status) values(15, 'Geburtstag', 0);
insert into mysteryword (card_id, word, status) values(16, 'Bäcker', 0);
insert into mysteryword (card_id, word, status) values(16, 'Parfüm', 0);
insert into mysteryword (card_id, word, status) values(16, 'Flamme', 0);
insert into mysteryword (card_id, word, status) values(16, 'Zombie', 0);
insert into mysteryword (card_id, word, status) values(16, 'Joker', 0);
insert into mysteryword (card_id, word, status) values(17, 'Buffy', 0);
insert into mysteryword (card_id, word, status) values(17, 'Vulkan', 0);
insert into mysteryword (card_id, word, status) values(17, 'Leidenschaft', 0);
insert into mysteryword (card_id, word, status) values(17, 'Hahn', 0);
insert into mysteryword (card_id, word, status) values(17, 'Elektrizität', 0);
insert into mysteryword (card_id, word, status) values(18, 'Genie', 0);
insert into mysteryword (card_id, word, status) values(18, 'Dracula', 0);
insert into mysteryword (card_id, word, status) values(18, 'Löwe', 0);
insert into mysteryword (card_id, word, status) values(18, 'Socke Freitag', 0);
insert into mysteryword (card_id, word, status) values(18, 'Pirat', 0);
insert into mysteryword (card_id, word, status) values(19, 'Ferien', 0);
insert into mysteryword (card_id, word, status) values(19, 'Elfe', 0);
insert into mysteryword (card_id, word, status) values(19, 'Magnet', 0);
insert into mysteryword (card_id, word, status) values(19, 'Gabel', 0);
insert into mysteryword (card_id, word, status) values(19, 'Sirup', 0);
