insert into card(id, drawn, language) values(1, false, 0);
insert into card(id, drawn, language) values(2, false, 0);
insert into card(id, drawn, language) values(3, false, 0);
insert into card(id, drawn, language) values(4, false, 0);
insert into card(id, drawn, language) values(5, false, 0);
insert into card(id, drawn, language) values(6, false, 0);
insert into card(id, drawn, language) values(7, false, 0);
insert into card(id, drawn, language) values(8, false, 0);
insert into card(id, drawn, language) values(9, false, 0);
insert into card(id, drawn, language) values(10, false, 0);
insert into card(id, drawn, language) values(11, false, 0);
insert into card(id, drawn, language) values(12, false, 0);
insert into card(id, drawn, language) values(13, false, 0);
insert into card(id, drawn, language) values(14, false, 0);
insert into card(id, drawn, language) values(15, false, 0);
insert into card(id, drawn, language) values(16, false, 0);
insert into card(id, drawn, language) values(17, false, 0);
insert into card(id, drawn, language) values(18, false, 0);
insert into card(id, drawn, language) values(19, false, 0);

insert into card(id, drawn, language) values(94, false, 1);
insert into card(id, drawn, language) values(95, false, 1);
insert into card(id, drawn, language) values(96, false, 1);
insert into card(id, drawn, language) values(97, false, 1);
insert into card(id, drawn, language) values(98, false, 1);
insert into card(id, drawn, language) values(99, false, 1);
insert into card(id, drawn, language) values(100, false, 1);
insert into card(id, drawn, language) values(101, false, 1);
insert into card(id, drawn, language) values(102, false, 1);
insert into card(id, drawn, language) values(103, false, 1);
insert into card(id, drawn, language) values(104, false, 1);
insert into card(id, drawn, language) values(105, false, 1);
insert into card(id, drawn, language) values(106, false, 1);
insert into card(id, drawn, language) values(107, false, 1);
insert into card(id, drawn, language) values(108, false, 1);
insert into card(id, drawn, language) values(109, false, 1);
insert into card(id, drawn, language) values(110, false, 1);
insert into card(id, drawn, language) values(111, false, 1);
insert into card(id, drawn, language) values(112, false, 1);
insert into card(id, drawn, language) values(113, false, 1);
insert into card(id, drawn, language) values(114, false, 1);
insert into card(id, drawn, language) values(115, false, 1);
insert into card(id, drawn, language) values(116, false, 1);
insert into card(id, drawn, language) values(117, false, 1);
insert into card(id, drawn, language) values(118, false, 1);
insert into card(id, drawn, language) values(119, false, 1);
insert into card(id, drawn, language) values(120, false, 1);
insert into card(id, drawn, language) values(121, false, 1);
insert into card(id, drawn, language) values(122, false, 1);
insert into card(id, drawn, language) values(123, false, 1);
insert into card(id, drawn, language) values(124, false, 1);
insert into card(id, drawn, language) values(125, false, 1);
insert into card(id, drawn, language) values(126, false, 1);
insert into card(id, drawn, language) values(127, false, 1);
insert into card(id, drawn, language) values(128, false, 1);
insert into card(id, drawn, language) values(129, false, 1);


insert into mysteryword (card_id, word, status) values(1, 'Alcatraz', 0);
insert into mysteryword (card_id, word, status) values(1, 'Rauch', 0);
insert into mysteryword (card_id, word, status) values(1, 'Haselnuss', 0);
insert into mysteryword (card_id, word, status) values(1, 'Diamant', 0);
insert into mysteryword (card_id, word, status) values(1, 'Rose', 0);
insert into mysteryword (card_id, word, status) values(2, 'Marionette', 0);
insert into mysteryword (card_id, word, status) values(2, 'Spiel', 0);
insert into mysteryword (card_id, word, status) values(2, 'Vegas', 0);
insert into mysteryword (card_id, word, status) values(2, 'Truhe', 0);
insert into mysteryword (card_id, word, status) values(2, 'Flugzeug', 0);
insert into mysteryword (card_id, word, status) values(3, 'Schnur', 0);
insert into mysteryword (card_id, word, status) values(3, 'Australien', 0);
insert into mysteryword (card_id, word, status) values(3, 'Schloss', 0);
insert into mysteryword (card_id, word, status) values(3, 'Wache', 0);
insert into mysteryword (card_id, word, status) values(3, 'Schaf', 0);
insert into mysteryword (card_id, word, status) values(4, 'Fleece', 0);
insert into mysteryword (card_id, word, status) values(4, 'Maus', 0);
insert into mysteryword (card_id, word, status) values(4, 'Kette', 0);
insert into mysteryword (card_id, word, status) values(4, 'Bauernhof', 0);
insert into mysteryword (card_id, word, status) values(4, 'Belgien', 0);
insert into mysteryword (card_id, word, status) values(5, 'Pfeffer', 0);
insert into mysteryword (card_id, word, status) values(5, 'Dreieck', 0);
insert into mysteryword (card_id, word, status) values(5, 'Puppe', 0);
insert into mysteryword (card_id, word, status) values(5, 'Italien', 0);
insert into mysteryword (card_id, word, status) values(5, 'Bühne', 0);
insert into mysteryword (card_id, word, status) values(6, 'Herz', 0);
insert into mysteryword (card_id, word, status) values(6, 'Moskau', 0);
insert into mysteryword (card_id, word, status) values(6, 'Billard', 0);
insert into mysteryword (card_id, word, status) values(6, 'Einhorn', 0);
insert into mysteryword (card_id, word, status) values(6, 'Orange', 0);
insert into mysteryword (card_id, word, status) values(7, 'Tokio', 0);
insert into mysteryword (card_id, word, status) values(7, 'Ferse', 0);
insert into mysteryword (card_id, word, status) values(7, 'Huhn', 0);
insert into mysteryword (card_id, word, status) values(7, 'Helikopter', 0);
insert into mysteryword (card_id, word, status) values(7, 'Offizier', 0);
insert into mysteryword (card_id, word, status) values(8, 'Melone', 0);
insert into mysteryword (card_id, word, status) values(8, 'Anker', 0);
insert into mysteryword (card_id, word, status) values(8, 'Israel', 0);
insert into mysteryword (card_id, word, status) values(8, 'Kaktus', 0);
insert into mysteryword (card_id, word, status) values(8, 'Tennis', 0);
insert into mysteryword (card_id, word, status) values(9, 'Frankreich', 0);
insert into mysteryword (card_id, word, status) values(9, 'Mond', 0);
insert into mysteryword (card_id, word, status) values(9, 'Kantine', 0);
insert into mysteryword (card_id, word, status) values(9, 'Kaiserpinguin', 0);
insert into mysteryword (card_id, word, status) values(9, 'Werkzeug', 0);
insert into mysteryword (card_id, word, status) values(10, 'Gehirn', 0);
insert into mysteryword (card_id, word, status) values(10, 'Maske', 0);
insert into mysteryword (card_id, word, status) values(10, 'Konzert', 0);
insert into mysteryword (card_id, word, status) values(10, 'Troja', 0);
insert into mysteryword (card_id, word, status) values(10, 'Hai', 0);
insert into mysteryword (card_id, word, status) values(11, 'Musik', 0);
insert into mysteryword (card_id, word, status) values(11, 'Hals', 0);
insert into mysteryword (card_id, word, status) values(11, 'Amerika', 0);
insert into mysteryword (card_id, word, status) values(11, 'Kaffee', 0);
insert into mysteryword (card_id, word, status) values(11, 'Fieber', 0);
insert into mysteryword (card_id, word, status) values(12, 'Barbie', 0);
insert into mysteryword (card_id, word, status) values(12, 'Schokolade', 0);
insert into mysteryword (card_id, word, status) values(12, 'Schnee', 0);
insert into mysteryword (card_id, word, status) values(12, 'Krawatte', 0);
insert into mysteryword (card_id, word, status) values(12, 'Wind', 0);
insert into mysteryword (card_id, word, status) values(13, 'Gedanke', 0);
insert into mysteryword (card_id, word, status) values(13, 'Frankenstein', 0);
insert into mysteryword (card_id, word, status) values(13, 'Strahl', 0);
insert into mysteryword (card_id, word, status) values(13, 'Akzent', 0);
insert into mysteryword (card_id, word, status) values(13, 'Dusche', 0);
insert into mysteryword (card_id, word, status) values(14, 'Marienkäfer', 0);
insert into mysteryword (card_id, word, status) values(14, 'Senf', 0);
insert into mysteryword (card_id, word, status) values(14, 'Sherlock', 0);
insert into mysteryword (card_id, word, status) values(14, 'Flasche', 0);
insert into mysteryword (card_id, word, status) values(14, 'Virus', 0);
insert into mysteryword (card_id, word, status) values(15, 'Gift', 0);
insert into mysteryword (card_id, word, status) values(15, 'Stern', 0);
insert into mysteryword (card_id, word, status) values(15, 'Wolf', 0);
insert into mysteryword (card_id, word, status) values(15, 'Lena', 0);
insert into mysteryword (card_id, word, status) values(15, 'Geburtstag', 0);
insert into mysteryword (card_id, word, status) values(16, 'Bäcker', 0);
insert into mysteryword (card_id, word, status) values(16, 'Parfüm', 0);
insert into mysteryword (card_id, word, status) values(16, 'Flamme', 0);
insert into mysteryword (card_id, word, status) values(16, 'Zombie', 0);
insert into mysteryword (card_id, word, status) values(16, 'Joker', 0);
insert into mysteryword (card_id, word, status) values(17, 'Buffy', 0);
insert into mysteryword (card_id, word, status) values(17, 'Vulkan', 0);
insert into mysteryword (card_id, word, status) values(17, 'Leidenschaft', 0);
insert into mysteryword (card_id, word, status) values(17, 'Hahn', 0);
insert into mysteryword (card_id, word, status) values(17, 'Elektrizität', 0);
insert into mysteryword (card_id, word, status) values(18, 'Genie', 0);
insert into mysteryword (card_id, word, status) values(18, 'Dracula', 0);
insert into mysteryword (card_id, word, status) values(18, 'Löwe', 0);
insert into mysteryword (card_id, word, status) values(18, 'Socke rFreitag', 0);
insert into mysteryword (card_id, word, status) values(18, 'Pirat', 0);
insert into mysteryword (card_id, word, status) values(19, 'Ferien', 0);
insert into mysteryword (card_id, word, status) values(19, 'Elfe', 0);
insert into mysteryword (card_id, word, status) values(19, 'Magnet', 0);
insert into mysteryword (card_id, word, status) values(19, 'Gabel', 0);
insert into mysteryword (card_id, word, status) values(19, 'Sirup', 0);

insert into mysteryword (card_id, word, status) values(94,'Wald', 1);
insert into mysteryword (card_id, word, status) values(94,'Waage', 1);
insert into mysteryword (card_id, word, status) values(94,'Zeus', 1);
insert into mysteryword (card_id, word, status) values(94,'Kakerlake', 1);
insert into mysteryword (card_id, word, status) values(94,'Dinosaurier', 1);
insert into mysteryword (card_id, word, status) values(95,'Gelb', 1);
insert into mysteryword (card_id, word, status) values(95,'Pilz', 1);
insert into mysteryword (card_id, word, status) values(95,'Taube', 1);
insert into mysteryword (card_id, word, status) values(95,'Pikachu', 1);
insert into mysteryword (card_id, word, status) values(95,'Asterix', 1);
insert into mysteryword (card_id, word, status) values(96,'Roboter', 1);
insert into mysteryword (card_id, word, status) values(96,'Komödie', 1);
insert into mysteryword (card_id, word, status) values(96,'Sprache', 1);
insert into mysteryword (card_id, word, status) values(96,'Friseur', 1);
insert into mysteryword (card_id, word, status) values(96,'Cocktail', 1);
insert into mysteryword (card_id, word, status) values(97,'Mario', 1);
insert into mysteryword (card_id, word, status) values(97,'Korken', 1);
insert into mysteryword (card_id, word, status) values(97,'Geige', 1);
insert into mysteryword (card_id, word, status) values(97,'Pfirsich', 1);
insert into mysteryword (card_id, word, status) values(97,'Fuchs', 1);
insert into mysteryword (card_id, word, status) values(98,'Polizei', 1);
insert into mysteryword (card_id, word, status) values(98,'Simpson', 1);
insert into mysteryword (card_id, word, status) values(98,'Donut', 1);
insert into mysteryword (card_id, word, status) values(98,'Zeitung', 1);
insert into mysteryword (card_id, word, status) values(98,'Berge', 1);
insert into mysteryword (card_id, word, status) values(99,'Erdnuss', 1);
insert into mysteryword (card_id, word, status) values(99,'Glühbirne', 1);
insert into mysteryword (card_id, word, status) values(99,'Jedi', 1);
insert into mysteryword (card_id, word, status) values(99,'Chili', 1);
insert into mysteryword (card_id, word, status) values(99,'Sombrero', 1);
insert into mysteryword (card_id, word, status) values(100,'Kleeblatt', 1);
insert into mysteryword (card_id, word, status) values(100,'Taste', 1);
insert into mysteryword (card_id, word, status) values(100,'Käse', 1);
insert into mysteryword (card_id, word, status) values(100,'Chewbacca', 1);
insert into mysteryword (card_id, word, status) values(100,'Revolver', 1);
insert into mysteryword (card_id, word, status) values(101,'Doktor', 1);
insert into mysteryword (card_id, word, status) values(101,'Erdbeere', 1);
insert into mysteryword (card_id, word, status) values(101,'Kernkraft', 1);
insert into mysteryword (card_id, word, status) values(101,'Lotterie', 1);
insert into mysteryword (card_id, word, status) values(101,'Friedhof', 1);
insert into mysteryword (card_id, word, status) values(102,'Amor', 1);
insert into mysteryword (card_id, word, status) values(102,'Regenschirm', 1);
insert into mysteryword (card_id, word, status) values(102,'Sprung', 1);
insert into mysteryword (card_id, word, status) values(102,'Wurzel', 1);
insert into mysteryword (card_id, word, status) values(102,'Schatz', 1);
insert into mysteryword (card_id, word, status) values(103,'Pilot', 1);
insert into mysteryword (card_id, word, status) values(103,'Micky', 1);
insert into mysteryword (card_id, word, status) values(103,'Kanalisation', 1);
insert into mysteryword (card_id, word, status) values(103,'Galaxie', 1);
insert into mysteryword (card_id, word, status) values(103,'Schnurrbart', 1);
insert into mysteryword (card_id, word, status) values(104,'Blase', 1);
insert into mysteryword (card_id, word, status) values(104,'Kette', 1);
insert into mysteryword (card_id, word, status) values(104,'Stark', 1);
insert into mysteryword (card_id, word, status) values(104,'Keks', 1);
insert into mysteryword (card_id, word, status) values(104,'Croissant', 1);
insert into mysteryword (card_id, word, status) values(105,'Geist', 1);
insert into mysteryword (card_id, word, status) values(105,'Stroh', 1);
insert into mysteryword (card_id, word, status) values(105,'Nagel', 1);
insert into mysteryword (card_id, word, status) values(105,'Potter', 1);
insert into mysteryword (card_id, word, status) values(105,'Darwin', 1);
insert into mysteryword (card_id, word, status) values(106,'Tomate', 1);
insert into mysteryword (card_id, word, status) values(106,'Fallschirm', 1);
insert into mysteryword (card_id, word, status) values(106,'Kanone', 1);
insert into mysteryword (card_id, word, status) values(106,'Fernglas', 1);
insert into mysteryword (card_id, word, status) values(106,'Fata Morgana', 1);
insert into mysteryword (card_id, word, status) values(107,'Ramses', 1);
insert into mysteryword (card_id, word, status) values(107,'Feuer', 1);
insert into mysteryword (card_id, word, status) values(107,'Kreuzung', 1);
insert into mysteryword (card_id, word, status) values(107,'Prinzessin', 1);
insert into mysteryword (card_id, word, status) values(107,'Raumschiff', 1);
insert into mysteryword (card_id, word, status) values(108,'Bowling', 1);
insert into mysteryword (card_id, word, status) values(108,'Churchill', 1);
insert into mysteryword (card_id, word, status) values(108,'Widder', 1);
insert into mysteryword (card_id, word, status) values(108,'Spion', 1);
insert into mysteryword (card_id, word, status) values(108,'Olympiade', 1);
insert into mysteryword (card_id, word, status) values(109,'Klettern', 1);
insert into mysteryword (card_id, word, status) values(109,'Anwalt', 1);
insert into mysteryword (card_id, word, status) values(109,'Tolkien', 1);
insert into mysteryword (card_id, word, status) values(109,'Fluss', 1);
insert into mysteryword (card_id, word, status) values(109,'Teppich', 1);
insert into mysteryword (card_id, word, status) values(110,'Pony', 1);
insert into mysteryword (card_id, word, status) values(110,'Krone', 1);
insert into mysteryword (card_id, word, status) values(110,'Neu', 1);
insert into mysteryword (card_id, word, status) values(110,'Tarantino', 1);
insert into mysteryword (card_id, word, status) values(110,'Heino', 1);
insert into mysteryword (card_id, word, status) values(111,'Ninja', 1);
insert into mysteryword (card_id, word, status) values(111,'Bettdecke', 1);
insert into mysteryword (card_id, word, status) values(111,'Jäger', 1);
insert into mysteryword (card_id, word, status) values(111,'Gemüse', 1);
insert into mysteryword (card_id, word, status) values(111,'Höhle', 1);
insert into mysteryword (card_id, word, status) values(112,'Hans', 1);
insert into mysteryword (card_id, word, status) values(112,'Casino', 1);
insert into mysteryword (card_id, word, status) values(112,'Bonbon', 1);
insert into mysteryword (card_id, word, status) values(112,'Brunnen', 1);
insert into mysteryword (card_id, word, status) values(112,'Licht', 1);
insert into mysteryword (card_id, word, status) values(113,'Sofa', 1);
insert into mysteryword (card_id, word, status) values(113,'Mozart', 1);
insert into mysteryword (card_id, word, status) values(113,'Ring', 1);
insert into mysteryword (card_id, word, status) values(113,'Pizza', 1);
insert into mysteryword (card_id, word, status) values(113,'Bild', 1);
insert into mysteryword (card_id, word, status) values(114,'Feuerwehr', 1);
insert into mysteryword (card_id, word, status) values(114,'Glas', 1);
insert into mysteryword (card_id, word, status) values(114,'Kloss', 1);
insert into mysteryword (card_id, word, status) values(114,'Griechenland', 1);
insert into mysteryword (card_id, word, status) values(114,'Tradition', 1);
insert into mysteryword (card_id, word, status) values(115,'Schlange', 1);
insert into mysteryword (card_id, word, status) values(115,'Pokal', 1);
insert into mysteryword (card_id, word, status) values(115,'Picasso', 1);
insert into mysteryword (card_id, word, status) values(115,'Uhr', 1);
insert into mysteryword (card_id, word, status) values(115,'Scheiterhaufen', 1);
insert into mysteryword (card_id, word, status) values(116,'Zauberer', 1);
insert into mysteryword (card_id, word, status) values(116,'Hockey', 1);
insert into mysteryword (card_id, word, status) values(116,'Banane', 1);
insert into mysteryword (card_id, word, status) values(116,'Helene', 1);
insert into mysteryword (card_id, word, status) values(116,'Caesar', 1);
insert into mysteryword (card_id, word, status) values(117,'Nudel', 1);
insert into mysteryword (card_id, word, status) values(117,'Hut', 1);
insert into mysteryword (card_id, word, status) values(117,'Zahnarzt', 1);
insert into mysteryword (card_id, word, status) values(117,'Weizen', 1);
insert into mysteryword (card_id, word, status) values(117,'Muschel', 1);
insert into mysteryword (card_id, word, status) values(118,'Shakespeare', 1);
insert into mysteryword (card_id, word, status) values(118,'Riese', 1);
insert into mysteryword (card_id, word, status) values(118,'Schaum', 1);
insert into mysteryword (card_id, word, status) values(118,'Keller', 1);
insert into mysteryword (card_id, word, status) values(118,'Messer', 1);
insert into mysteryword (card_id, word, status) values(119,'Kissen', 1);
insert into mysteryword (card_id, word, status) values(119,'Armstrong', 1);
insert into mysteryword (card_id, word, status) values(119,'Schwert', 1);
insert into mysteryword (card_id, word, status) values(119,'Flug', 1);
insert into mysteryword (card_id, word, status) values(119,'Ticket', 1);
insert into mysteryword (card_id, word, status) values(120,'Pinguin', 1);
insert into mysteryword (card_id, word, status) values(120,'Zelle', 1);
insert into mysteryword (card_id, word, status) values(120,'Gandhi', 1);
insert into mysteryword (card_id, word, status) values(120,'Oase', 1);
insert into mysteryword (card_id, word, status) values(120,'Krokodil', 1);
insert into mysteryword (card_id, word, status) values(121,'Schmuck', 1);
insert into mysteryword (card_id, word, status) values(121,'U-Bahn', 1);
insert into mysteryword (card_id, word, status) values(121,'Brille', 1);
insert into mysteryword (card_id, word, status) values(121,'Falco', 1);
insert into mysteryword (card_id, word, status) values(121,'Jackson', 1);
insert into mysteryword (card_id, word, status) values(122,'Zigarette', 1);
insert into mysteryword (card_id, word, status) values(122,'Armband', 1);
insert into mysteryword (card_id, word, status) values(122,'Wetterbericht', 1);
insert into mysteryword (card_id, word, status) values(122,'Turm', 1);
insert into mysteryword (card_id, word, status) values(122,'Tattoo', 1);
insert into mysteryword (card_id, word, status) values(123,'Spielberg', 1);
insert into mysteryword (card_id, word, status) values(123,'Apfel', 1);
insert into mysteryword (card_id, word, status) values(123,'Meerjungfrau', 1);
insert into mysteryword (card_id, word, status) values(123,'Boxen', 1);
insert into mysteryword (card_id, word, status) values(123,'Zwerg', 1);
insert into mysteryword (card_id, word, status) values(124,'Zirkus', 1);
insert into mysteryword (card_id, word, status) values(124,'Elvis', 1);
insert into mysteryword (card_id, word, status) values(124,'Rasenmäher', 1);
insert into mysteryword (card_id, word, status) values(124,'Stein', 1);
insert into mysteryword (card_id, word, status) values(124,'Zug', 1);
insert into mysteryword (card_id, word, status) values(125,'Sardine', 1);
insert into mysteryword (card_id, word, status) values(125,'Stück', 1);
insert into mysteryword (card_id, word, status) values(125,'Kleopatra', 1);
insert into mysteryword (card_id, word, status) values(125,'Fenster', 1);
insert into mysteryword (card_id, word, status) values(125,'Granatapfel', 1);
insert into mysteryword (card_id, word, status) values(126,'Füllung', 1);
insert into mysteryword (card_id, word, status) values(126,'Bürste', 1);
insert into mysteryword (card_id, word, status) values(126,'Schwein', 1);
insert into mysteryword (card_id, word, status) values(126,'Avicii', 1);
insert into mysteryword (card_id, word, status) values(126,'Hausschuh', 1);
insert into mysteryword (card_id, word, status) values(127,'Blatt', 1);
insert into mysteryword (card_id, word, status) values(127,'Puma', 1);
insert into mysteryword (card_id, word, status) values(127,'Revolution', 1);
insert into mysteryword (card_id, word, status) values(127,'Sahara', 1);
insert into mysteryword (card_id, word, status) values(127,'Ritter', 1);
insert into mysteryword (card_id, word, status) values(128,'Frieden', 1);
insert into mysteryword (card_id, word, status) values(128,'Blume', 1);
insert into mysteryword (card_id, word, status) values(128,'Schweiz', 1);
insert into mysteryword (card_id, word, status) values(128,'Kalender', 1);
insert into mysteryword (card_id, word, status) values(128,'Schnitzel', 1);
insert into mysteryword (card_id, word, status) values(129,'Kanada', 1);
insert into mysteryword (card_id, word, status) values(129,'Zoo', 1);
insert into mysteryword (card_id, word, status) values(129,'Pfeife', 1);
insert into mysteryword (card_id, word, status) values(129,'Buch', 1);
insert into mysteryword (card_id, word, status) values(129,'Meerrettich', 1);

/* English words*/

insert into card(id, drawn, language) values(20, false, 1);
insert into card(id, drawn, language) values(21, false, 1);
insert into card(id, drawn, language) values(22, false, 1);
insert into card(id, drawn, language) values(23, false, 1);
insert into card(id, drawn, language) values(24, false, 1);
insert into card(id, drawn, language) values(25, false, 1);
insert into card(id, drawn, language) values(26, false, 1);
insert into card(id, drawn, language) values(27, false, 1);
insert into card(id, drawn, language) values(28, false, 1);
insert into card(id, drawn, language) values(29, false, 1);
insert into card(id, drawn, language) values(30, false, 1);
insert into card(id, drawn, language) values(31, false, 1);
insert into card(id, drawn, language) values(32, false, 1);
insert into card(id, drawn, language) values(33, false, 1);
insert into card(id, drawn, language) values(34, false, 1);
insert into card(id, drawn, language) values(35, false, 1);
insert into card(id, drawn, language) values(36, false, 1);
insert into card(id, drawn, language) values(37, false, 1);
insert into card(id, drawn, language) values(38, false, 1);
insert into card(id, drawn, language) values(39, false, 1);
insert into card(id, drawn, language) values(40, false, 1);
insert into card(id, drawn, language) values(41, false, 1);
insert into card(id, drawn, language) values(42, false, 1);
insert into card(id, drawn, language) values(43, false, 1);
insert into card(id, drawn, language) values(44, false, 1);
insert into card(id, drawn, language) values(45, false, 1);
insert into card(id, drawn, language) values(46, false, 1);
insert into card(id, drawn, language) values(47, false, 1);
insert into card(id, drawn, language) values(48, false, 1);
insert into card(id, drawn, language) values(49, false, 1);
insert into card(id, drawn, language) values(50, false, 1);
insert into card(id, drawn, language) values(51, false, 1);
insert into card(id, drawn, language) values(52, false, 1);
insert into card(id, drawn, language) values(53, false, 1);
insert into card(id, drawn, language) values(54, false, 1);
insert into card(id, drawn, language) values(55, false, 1);
insert into card(id, drawn, language) values(56, false, 1);
insert into card(id, drawn, language) values(57, false, 1);
insert into card(id, drawn, language) values(58, false, 1);
insert into card(id, drawn, language) values(59, false, 1);
insert into card(id, drawn, language) values(60, false, 1);
insert into card(id, drawn, language) values(61, false, 1);
insert into card(id, drawn, language) values(62, false, 1);
insert into card(id, drawn, language) values(63, false, 1);
insert into card(id, drawn, language) values(64, false, 1);
insert into card(id, drawn, language) values(65, false, 1);
insert into card(id, drawn, language) values(66, false, 1);
insert into card(id, drawn, language) values(67, false, 1);
insert into card(id, drawn, language) values(68, false, 1);
insert into card(id, drawn, language) values(69, false, 1);
insert into card(id, drawn, language) values(70, false, 1);
insert into card(id, drawn, language) values(71, false, 1);
insert into card(id, drawn, language) values(72, false, 1);
insert into card(id, drawn, language) values(73, false, 1);
insert into card(id, drawn, language) values(74, false, 1);


insert into mysteryword (card_id, word, status) values(20,'Alcatraz',1);
insert into mysteryword (card_id, word, status) values(20,'Smoke',1);
insert into mysteryword (card_id, word, status) values(20,'Hazelnut',1);
insert into mysteryword (card_id, word, status) values(20,'Diamond',1);
insert into mysteryword (card_id, word, status) values(20,'Rose',1);
insert into mysteryword (card_id, word, status) values(21,'Puppet',1);
insert into mysteryword (card_id, word, status) values(21,'Game',1);
insert into mysteryword (card_id, word, status) values(21,'Vegas',1);
insert into mysteryword (card_id, word, status) values(21,'Chest',1);
insert into mysteryword (card_id, word, status) values(21,'Airplane',1);
insert into mysteryword (card_id, word, status) values(22,'Cord',1);
insert into mysteryword (card_id, word, status) values(22,'Australia',1);
insert into mysteryword (card_id, word, status) values(22,'Castle',1);
insert into mysteryword (card_id, word, status) values(22,'Guard',1);
insert into mysteryword (card_id, word, status) values(22,'Sheep',1);
insert into mysteryword (card_id, word, status) values(23,'Fleece',1);
insert into mysteryword (card_id, word, status) values(23,'Mouse',1);
insert into mysteryword (card_id, word, status) values(23,'Chain',1);
insert into mysteryword (card_id, word, status) values(23,'Farm',1);
insert into mysteryword (card_id, word, status) values(23,'Belgium',1);
insert into mysteryword (card_id, word, status) values(24,'Pepper',1);
insert into mysteryword (card_id, word, status) values(24,'Triangle',1);
insert into mysteryword (card_id, word, status) values(24,'Doll',1);
insert into mysteryword (card_id, word, status) values(24,'Italy',1);
insert into mysteryword (card_id, word, status) values(24,'Stage',1);
insert into mysteryword (card_id, word, status) values(25,'Heart',1);
insert into mysteryword (card_id, word, status) values(25,'Moscow',1);
insert into mysteryword (card_id, word, status) values(25,'Billiards',1);
insert into mysteryword (card_id, word, status) values(25,'Unicorn',1);
insert into mysteryword (card_id, word, status) values(25,'Orange',1);
insert into mysteryword (card_id, word, status) values(26,'Tokyo',1);
insert into mysteryword (card_id, word, status) values(26,'Heel',1);
insert into mysteryword (card_id, word, status) values(26,'Chicken',1);
insert into mysteryword (card_id, word, status) values(26,'Helicopter',1);
insert into mysteryword (card_id, word, status) values(26,'Officer',1);
insert into mysteryword (card_id, word, status) values(27,'Melon',1);
insert into mysteryword (card_id, word, status) values(27,'Anchor',1);
insert into mysteryword (card_id, word, status) values(27,'Israel',1);
insert into mysteryword (card_id, word, status) values(27,'Cactus',1);
insert into mysteryword (card_id, word, status) values(27,'Tennis',1);
insert into mysteryword (card_id, word, status) values(28,'France',1);
insert into mysteryword (card_id, word, status) values(28,'Moon',1);
insert into mysteryword (card_id, word, status) values(28,'Canteen',1);
insert into mysteryword (card_id, word, status) values(28,'Emperor penguin',1);
insert into mysteryword (card_id, word, status) values(28,'Tool',1);
insert into mysteryword (card_id, word, status) values(29,'Brain',1);
insert into mysteryword (card_id, word, status) values(29,'Mask',1);
insert into mysteryword (card_id, word, status) values(29,'Concert',1);
insert into mysteryword (card_id, word, status) values(29,'Troy',1);
insert into mysteryword (card_id, word, status) values(29,'Shark',1);
insert into mysteryword (card_id, word, status) values(30,'Music',1);
insert into mysteryword (card_id, word, status) values(30,'Neck',1);
insert into mysteryword (card_id, word, status) values(30,'America',1);
insert into mysteryword (card_id, word, status) values(30,'Coffee',1);
insert into mysteryword (card_id, word, status) values(30,'Fever',1);
insert into mysteryword (card_id, word, status) values(31,'Barbie',1);
insert into mysteryword (card_id, word, status) values(31,'Chocolate',1);
insert into mysteryword (card_id, word, status) values(31,'Snow',1);
insert into mysteryword (card_id, word, status) values(31,'Tie',1);
insert into mysteryword (card_id, word, status) values(31,'Wind',1);
insert into mysteryword (card_id, word, status) values(32,'Thought',1);
insert into mysteryword (card_id, word, status) values(32,'Frankenstein',1);
insert into mysteryword (card_id, word, status) values(32,'Beam',1);
insert into mysteryword (card_id, word, status) values(32,'Accent',1);
insert into mysteryword (card_id, word, status) values(32,'Shower',1);
insert into mysteryword (card_id, word, status) values(33,'Ladybird',1);
insert into mysteryword (card_id, word, status) values(33,'Mustard',1);
insert into mysteryword (card_id, word, status) values(33,'Sherlock',1);
insert into mysteryword (card_id, word, status) values(33,'Bottle',1);
insert into mysteryword (card_id, word, status) values(33,'Virus',1);
insert into mysteryword (card_id, word, status) values(34,'Poison',1);
insert into mysteryword (card_id, word, status) values(34,'Star',1);
insert into mysteryword (card_id, word, status) values(34,'Wolf',1);
insert into mysteryword (card_id, word, status) values(34,'Lena',1);
insert into mysteryword (card_id, word, status) values(34,'Birthday',1);
insert into mysteryword (card_id, word, status) values(35,'Baker',1);
insert into mysteryword (card_id, word, status) values(35,'Perfume',1);
insert into mysteryword (card_id, word, status) values(35,'Flame',1);
insert into mysteryword (card_id, word, status) values(35,'Zombie',1);
insert into mysteryword (card_id, word, status) values(35,'Joker',1);
insert into mysteryword (card_id, word, status) values(36,'Buffy',1);
insert into mysteryword (card_id, word, status) values(36,'Volcano',1);
insert into mysteryword (card_id, word, status) values(36,'Passion',1);
insert into mysteryword (card_id, word, status) values(36,'Cock',1);
insert into mysteryword (card_id, word, status) values(36,'Electricity',1);
insert into mysteryword (card_id, word, status) values(37,'Genius',1);
insert into mysteryword (card_id, word, status) values(37,'Dracula',1);
insert into mysteryword (card_id, word, status) values(37,'Lion',1);
insert into mysteryword (card_id, word, status) values(37,'Sock',1);
insert into mysteryword (card_id, word, status) values(37,'Friday',1);
insert into mysteryword (card_id, word, status) values(38,'Pirate',1);
insert into mysteryword (card_id, word, status) values(38,'Holidays',1);
insert into mysteryword (card_id, word, status) values(38,'Fairy',1);
insert into mysteryword (card_id, word, status) values(38,'Magnet',1);
insert into mysteryword (card_id, word, status) values(38,'Fork',1);
insert into mysteryword (card_id, word, status) values(39,'Syrup',1);
insert into mysteryword (card_id, word, status) values(39,'Forest',1);
insert into mysteryword (card_id, word, status) values(39,'Scale',1);
insert into mysteryword (card_id, word, status) values(39,'Zeus',1);
insert into mysteryword (card_id, word, status) values(39,'Cockroach',1);
insert into mysteryword (card_id, word, status) values(40,'Dinosaur',1);
insert into mysteryword (card_id, word, status) values(40,'Yellow',1);
insert into mysteryword (card_id, word, status) values(40,'Mushroom',1);
insert into mysteryword (card_id, word, status) values(40,'Pigeon',1);
insert into mysteryword (card_id, word, status) values(40,'Pikachu',1);
insert into mysteryword (card_id, word, status) values(41,'Asterix',1);
insert into mysteryword (card_id, word, status) values(41,'Robots',1);
insert into mysteryword (card_id, word, status) values(41,'Comedy',1);
insert into mysteryword (card_id, word, status) values(41,'Language',1);
insert into mysteryword (card_id, word, status) values(41,'Hairdresser',1);
insert into mysteryword (card_id, word, status) values(42,'Cocktail',1);
insert into mysteryword (card_id, word, status) values(42,'Mario',1);
insert into mysteryword (card_id, word, status) values(42,'Cork',1);
insert into mysteryword (card_id, word, status) values(42,'Violin',1);
insert into mysteryword (card_id, word, status) values(42,'Peach',1);
insert into mysteryword (card_id, word, status) values(43,'Fox',1);
insert into mysteryword (card_id, word, status) values(43,'Police',1);
insert into mysteryword (card_id, word, status) values(43,'Simpson',1);
insert into mysteryword (card_id, word, status) values(43,'Donut',1);
insert into mysteryword (card_id, word, status) values(43,'Newspaper',1);
insert into mysteryword (card_id, word, status) values(44,'Mountains',1);
insert into mysteryword (card_id, word, status) values(44,'Peanut',1);
insert into mysteryword (card_id, word, status) values(44,'Light bulb',1);
insert into mysteryword (card_id, word, status) values(44,'Jedi',1);
insert into mysteryword (card_id, word, status) values(44,'Chili',1);
insert into mysteryword (card_id, word, status) values(45,'Sombrero',1);
insert into mysteryword (card_id, word, status) values(45,'Cloverleaf',1);
insert into mysteryword (card_id, word, status) values(45,'Button',1);
insert into mysteryword (card_id, word, status) values(45,'Cheese',1);
insert into mysteryword (card_id, word, status) values(45,'Chewbacca',1);
insert into mysteryword (card_id, word, status) values(46,'Revolver',1);
insert into mysteryword (card_id, word, status) values(46,'Doctor',1);
insert into mysteryword (card_id, word, status) values(46,'Strawberry',1);
insert into mysteryword (card_id, word, status) values(46,'Nuclear power',1);
insert into mysteryword (card_id, word, status) values(46,'Lottery',1);
insert into mysteryword (card_id, word, status) values(47,'Cemetery',1);
insert into mysteryword (card_id, word, status) values(47,'Cupid',1);
insert into mysteryword (card_id, word, status) values(47,'Umbrella',1);
insert into mysteryword (card_id, word, status) values(47,'Jump',1);
insert into mysteryword (card_id, word, status) values(47,'Root',1);
insert into mysteryword (card_id, word, status) values(48,'Treasure',1);
insert into mysteryword (card_id, word, status) values(48,'Pilot',1);
insert into mysteryword (card_id, word, status) values(48,'Mickey',1);
insert into mysteryword (card_id, word, status) values(48,'Sewerage',1);
insert into mysteryword (card_id, word, status) values(48,'Galaxy',1);
insert into mysteryword (card_id, word, status) values(49,'Moustache',1);
insert into mysteryword (card_id, word, status) values(49,'Bubble',1);
insert into mysteryword (card_id, word, status) values(49,'Chain',1);
insert into mysteryword (card_id, word, status) values(49,'Strong',1);
insert into mysteryword (card_id, word, status) values(49,'Cookie',1);
insert into mysteryword (card_id, word, status) values(50,'Croissant',1);
insert into mysteryword (card_id, word, status) values(50,'Spirit',1);
insert into mysteryword (card_id, word, status) values(50,'Straw',1);
insert into mysteryword (card_id, word, status) values(50,'Nail',1);
insert into mysteryword (card_id, word, status) values(50,'Potter',1);
insert into mysteryword (card_id, word, status) values(51,'Darwin',1);
insert into mysteryword (card_id, word, status) values(51,'Tomato',1);
insert into mysteryword (card_id, word, status) values(51,'Parachute',1);
insert into mysteryword (card_id, word, status) values(51,'Cannon',1);
insert into mysteryword (card_id, word, status) values(51,'Binoculars',1);
insert into mysteryword (card_id, word, status) values(52,'Fata morgana',1);
insert into mysteryword (card_id, word, status) values(52,'Ramses',1);
insert into mysteryword (card_id, word, status) values(52,'Fire',1);
insert into mysteryword (card_id, word, status) values(52,'Intersection',1);
insert into mysteryword (card_id, word, status) values(52,'Princess',1);
insert into mysteryword (card_id, word, status) values(53,'Spaceship',1);
insert into mysteryword (card_id, word, status) values(53,'Bowling',1);
insert into mysteryword (card_id, word, status) values(53,'Churchill',1);
insert into mysteryword (card_id, word, status) values(53,'Aries',1);
insert into mysteryword (card_id, word, status) values(53,'Spy',1);
insert into mysteryword (card_id, word, status) values(54,'Olympics',1);
insert into mysteryword (card_id, word, status) values(54,'Climbing',1);
insert into mysteryword (card_id, word, status) values(54,'Lawyer',1);
insert into mysteryword (card_id, word, status) values(54,'Tolkien',1);
insert into mysteryword (card_id, word, status) values(54,'River',1);
insert into mysteryword (card_id, word, status) values(55,'Carpet',1);
insert into mysteryword (card_id, word, status) values(55,'Pony',1);
insert into mysteryword (card_id, word, status) values(55,'Crown',1);
insert into mysteryword (card_id, word, status) values(55,'New',1);
insert into mysteryword (card_id, word, status) values(55,'Tarantino',1);
insert into mysteryword (card_id, word, status) values(56,'Heino',1);
insert into mysteryword (card_id, word, status) values(56,'Ninja',1);
insert into mysteryword (card_id, word, status) values(56,'Duvet',1);
insert into mysteryword (card_id, word, status) values(56,'Hunter',1);
insert into mysteryword (card_id, word, status) values(56,'Vegetables',1);
insert into mysteryword (card_id, word, status) values(57,'Cave',1);
insert into mysteryword (card_id, word, status) values(57,'Hans',1);
insert into mysteryword (card_id, word, status) values(57,'Casino',1);
insert into mysteryword (card_id, word, status) values(57,'Candy',1);
insert into mysteryword (card_id, word, status) values(57,'Fountain',1);
insert into mysteryword (card_id, word, status) values(58,'Light',1);
insert into mysteryword (card_id, word, status) values(58,'Sofa',1);
insert into mysteryword (card_id, word, status) values(58,'Mozart',1);
insert into mysteryword (card_id, word, status) values(58,'Ring',1);
insert into mysteryword (card_id, word, status) values(58,'Pizza',1);
insert into mysteryword (card_id, word, status) values(59,'Picture',1);
insert into mysteryword (card_id, word, status) values(59,'Fire department',1);
insert into mysteryword (card_id, word, status) values(59,'Glass',1);
insert into mysteryword (card_id, word, status) values(59,'Meatball',1);
insert into mysteryword (card_id, word, status) values(59,'Greece',1);
insert into mysteryword (card_id, word, status) values(60,'Tradition',1);
insert into mysteryword (card_id, word, status) values(60,'Snake',1);
insert into mysteryword (card_id, word, status) values(60,'Trophy',1);
insert into mysteryword (card_id, word, status) values(60,'Picasso',1);
insert into mysteryword (card_id, word, status) values(60,'Clock',1);
insert into mysteryword (card_id, word, status) values(61,'Pyre',1);
insert into mysteryword (card_id, word, status) values(61,'Wizard',1);
insert into mysteryword (card_id, word, status) values(61,'Hockey',1);
insert into mysteryword (card_id, word, status) values(61,'Banana',1);
insert into mysteryword (card_id, word, status) values(61,'Helene',1);
insert into mysteryword (card_id, word, status) values(62,'Caesar',1);
insert into mysteryword (card_id, word, status) values(62,'Noodle',1);
insert into mysteryword (card_id, word, status) values(62,'Hat',1);
insert into mysteryword (card_id, word, status) values(62,'Dentist',1);
insert into mysteryword (card_id, word, status) values(62,'Wheat',1);
insert into mysteryword (card_id, word, status) values(63,'Mussel',1);
insert into mysteryword (card_id, word, status) values(63,'Shakespeare',1);
insert into mysteryword (card_id, word, status) values(63,'Giant',1);
insert into mysteryword (card_id, word, status) values(63,'Foam',1);
insert into mysteryword (card_id, word, status) values(63,'Cellar',1);
insert into mysteryword (card_id, word, status) values(64,'Knives',1);
insert into mysteryword (card_id, word, status) values(64,'Pillows',1);
insert into mysteryword (card_id, word, status) values(64,'Armstrong',1);
insert into mysteryword (card_id, word, status) values(64,'Sword',1);
insert into mysteryword (card_id, word, status) values(64,'Flight',1);
insert into mysteryword (card_id, word, status) values(65,'Ticket',1);
insert into mysteryword (card_id, word, status) values(65,'Penguin',1);
insert into mysteryword (card_id, word, status) values(65,'Cell',1);
insert into mysteryword (card_id, word, status) values(65,'Gandhi',1);
insert into mysteryword (card_id, word, status) values(65,'Oasis',1);
insert into mysteryword (card_id, word, status) values(66,'Crocodile',1);
insert into mysteryword (card_id, word, status) values(66,'Jewellery',1);
insert into mysteryword (card_id, word, status) values(66,'Subway',1);
insert into mysteryword (card_id, word, status) values(66,'Glasses',1);
insert into mysteryword (card_id, word, status) values(66,'Falco',1);
insert into mysteryword (card_id, word, status) values(67,'Jackson',1);
insert into mysteryword (card_id, word, status) values(67,'Cigarette',1);
insert into mysteryword (card_id, word, status) values(67,'Bracelet',1);
insert into mysteryword (card_id, word, status) values(67,'Weather forecast',1);
insert into mysteryword (card_id, word, status) values(67,'Tower',1);
insert into mysteryword (card_id, word, status) values(68,'Tattoo',1);
insert into mysteryword (card_id, word, status) values(68,'Spielberg',1);
insert into mysteryword (card_id, word, status) values(68,'Apple',1);
insert into mysteryword (card_id, word, status) values(68,'Mermaid',1);
insert into mysteryword (card_id, word, status) values(68,'Boxes',1);
insert into mysteryword (card_id, word, status) values(69,'Dwarf',1);
insert into mysteryword (card_id, word, status) values(69,'Circus',1);
insert into mysteryword (card_id, word, status) values(69,'Elvis',1);
insert into mysteryword (card_id, word, status) values(69,'Lawn mower',1);
insert into mysteryword (card_id, word, status) values(69,'Stone',1);
insert into mysteryword (card_id, word, status) values(70,'Train',1);
insert into mysteryword (card_id, word, status) values(70,'Sardine',1);
insert into mysteryword (card_id, word, status) values(70,'Piece',1);
insert into mysteryword (card_id, word, status) values(70,'Cleopatra',1);
insert into mysteryword (card_id, word, status) values(70,'Window',1);
insert into mysteryword (card_id, word, status) values(71,'Pomegranate',1);
insert into mysteryword (card_id, word, status) values(71,'Filling',1);
insert into mysteryword (card_id, word, status) values(71,'Brush',1);
insert into mysteryword (card_id, word, status) values(71,'Pig',1);
insert into mysteryword (card_id, word, status) values(71,'Avicii',1);
insert into mysteryword (card_id, word, status) values(72,'Slipper',1);
insert into mysteryword (card_id, word, status) values(72,'Sheet',1);
insert into mysteryword (card_id, word, status) values(72,'Puma',1);
insert into mysteryword (card_id, word, status) values(72,'Revolution',1);
insert into mysteryword (card_id, word, status) values(72,'Sahara',1);
insert into mysteryword (card_id, word, status) values(73,'Knight',1);
insert into mysteryword (card_id, word, status) values(73,'Peace',1);
insert into mysteryword (card_id, word, status) values(73,'Flower',1);
insert into mysteryword (card_id, word, status) values(73,'Switzerland',1);
insert into mysteryword (card_id, word, status) values(73,'Calendar',1);
insert into mysteryword (card_id, word, status) values(74,'Schnitzel',1);
insert into mysteryword (card_id, word, status) values(74,'Canada',1);
insert into mysteryword (card_id, word, status) values(74,'Zoo',1);
insert into mysteryword (card_id, word, status) values(74,'Whistle',1);
insert into mysteryword (card_id, word, status) values(74,'Book',1);

